---
title: "Fig 6"
author: "Qin"
date: "2018/11/7"
output: html_document
---

```{r warning=FALSE, message=FALSE}
setwd("/mnt/bai/qinyuan/xiaoxuan/QA/")
print(paste("Your working directory is in",getwd()))
rm(list=ls()) 

library(ggplot2)
library(ggpubr)
library(dplyr)
```



## Fig 6e

```{r}
data = read.table("./data/Fig6e_2.txt",header = T, row.names = 1)
head(data)

data_ra <- filter(data, method == "ra")
data_aa <- filter(data, method == "aa")
```

```{r}
com_ra_w <- compare_means( count ~ treatment, data = data_ra, method = "wilcox.test", paired=FALSE)
com_ra_t <- compare_means( count ~ treatment, data = data_ra, method = "t.test", paired=FALSE)
com_ra <- rbind(com_ra_w, com_ra_t)
head(com_ra)

p <- ggboxplot(data_ra, x="treatment",
               y = "count", color = "treatment",order = c("disease","health"),
               palette =  "uchicago", add = "jitter",short.panel.labs = FALSE)
# 添加p值
p01 <- p + stat_compare_means(aes(label = ..p.signif..), method = "wilcox.test",label.x = 1.5)

p01

write.table(com_ra, file = "./result/Fig6e-1-2.txt",sep = '\t',row.names = T)
ggsave(paste("./result/Fig6e-1-2.pdf", sep=""), p01, width = 2.5, height = 8)
```

```{r}
com_aa_w <- compare_means( count ~ treatment, data = data_aa, method = "wilcox.test", paired=FALSE)
com_aa_t <- compare_means( count ~ treatment, data = data_aa, method = "t.test", paired=FALSE)
com_aa <- rbind(com_aa_w, com_aa_t)
head(com_aa)

p2 <- ggboxplot(data_aa, x="treatment",
               y = "count", color = "treatment",order = c("disease","health"),
               palette = "uchicago", add = "jitter", short.panel.labs = FALSE)
# 添加p值
p02 <- p2 + stat_compare_means(aes(label = ..p.signif..), method = "wilcox.test",label.x = 1.5)

p02
write.table(com_aa, file = "./result/Fig6e-2-2.txt",sep = '\t',row.names = T)
ggsave(paste("./result/Fig6e-2-2.pdf", sep=""), p02, width = 2.5, height = 8)
```

## Fig 6f



```{r}
data_ra_6f <- read.csv("data/Fig6f-ra.csv", header = T)
head(data_ra_6f)
data_aa_6f <- read.csv("data/Fig6f-aa.csv", header = T)
head(data_aa_6f)
```

```{r}
com_ra6f_w <- compare_means( RA ~ Treatment, data = data_ra_6f, method = "wilcox.test", paired=FALSE)
com_ra6f_t <- compare_means( RA ~ Treatment, data = data_ra_6f, method = "t.test", paired=FALSE)
com_ra6f <- rbind(com_ra6f_w, com_ra6f_t)
head(com_ra6f)

p <- ggboxplot(data_ra_6f, x="Treatment",
               y = "RA", color = "Treatment",
               palette =  "uchicago", add = "jitter", short.panel.labs = FALSE) +
  labs(x="OTU_45", y="Relative genus abundance (RA) (‰)")

# 添加p值
p01 <- p + stat_compare_means(aes(label = ..p.signif..), method = "wilcox.test",label.x = 1.5)

p01

write.table(com_ra6f, file = "./result/Fig6f_ra.txt",sep = '\t',row.names = T)
ggsave(paste("./result/Fig6f_ra.pdf", sep=""), p01, width = 2.5, height = 8)
```


```{r}
com_aa6f_w <- compare_means( AA ~ Treatment, data = data_aa_6f, method = "wilcox.test", paired=FALSE)
com_aa6f_t <- compare_means( AA ~ Treatment, data = data_aa_6f, method = "t.test", paired=FALSE)
com_aa6f <- rbind(com_aa6f_w, com_aa6f_t)
head(com_aa6f)

p2 <- ggboxplot(data_aa_6f, x="Treatment",
               y = "AA", color = "Treatment",
               palette =  "uchicago", add = "jitter", short.panel.labs = FALSE) +
  labs(x="OTU_45", y="Quantitative genus abundance (QA)")
# 添加p值
p02 <- p2 + stat_compare_means(aes(label = ..p.signif..), method = "wilcox.test",label.x = 1.5)

p02
write.table(com_aa6f, file = "./result/Fig6f-aa.txt",sep = '\t',row.names = T)
ggsave(paste("./result/Fig6f-aa.pdf", sep=""), p02, width = 2.5, height = 8)
```


## Fig 5c new
```{r}
data5c = read.table("./data/Fig5c_new.txt",header = T, row.names = 1)
head(data5c)
data5c_stat  = read.table("./data/Fig5c_new_stat.txt",header = T, row.names = 1)
head(data5c_stat)
```
```{r}
com_5c_w <- compare_means( ratio ~ treatment, data = data5c, method = "wilcox.test", paired=FALSE,  group.by = "genotype")
com_5c_t <- compare_means( ratio ~ treatment, data = data5c, method = "t.test", paired=FALSE,  group.by = "genotype")
com_5c <- rbind(com_5c_w, com_5c_t)
head(com_5c)

write.table(com_5c, file = "./result/Fig5c_new_stat.txt",sep = '\t',row.names = T)
```


```{r}
p = ggplot(data5c_stat, aes(x = treatment, y = radio_mean)) + 
  geom_bar(stat = "identity",fill = "white", colour = "black", width=0.7, na.rm = TRUE)+ 
  geom_errorbar(aes(ymin= radio_mean - radio_error, ymax= radio_mean + radio_error), width=.1) + 
  facet_wrap(~genotype)+
  xlab("Groups")+
  ylab("Ratio of bacteria to host plant")+
  theme_bw()
p

ggsave(paste("./result/Fig5c_new.pdf", sep=""), p, width = 5, height = 8)
```


## Fig 5? dry wet rice


```{r}
load <- read.csv("data/Fig5f_sample.csv", header = T)
head(load)
data_AH <- filter(load, Site == "AH")
data_HN <- filter(load, Site == "HN")
data_AH_BAC <- filter(data_AH, Micro == "bac")
data_AH_FUN <- filter(data_AH, Micro == "fungi")
data_AH_SUM <- filter(data_AH, Micro == "bacfun")

data_HN_BAC <- filter(data_HN, Micro == "bac")
data_HN_FUN <- filter(data_HN, Micro == "fungi")
data_HN_SUM <- filter(data_HN, Micro == "bacfun")
```

```{r}
com_AH_BAC <- compare_means( load ~ Type, data = data_AH_BAC, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
com_AH_FUN <- compare_means( load ~ Type, data = data_AH_FUN, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
com_AH_SUM <- compare_means( load ~ Type, data = data_AH_SUM, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
head(com_AH_FUN)
head(com_AH_BAC)
head(com_AH_SUM)
com_HN_BAC <- compare_means( load ~ Type, data = data_HN_BAC, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
com_HN_FUN <- compare_means( load ~ Type, data = data_HN_FUN, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
com_HN_SUM <- compare_means( load ~ Type, data = data_HN_SUM, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
head(com_HN_SUM)
head(com_HN_FUN)
head(com_HN_BAC)

com <- rbind(com_AH_BAC, com_AH_FUN, com_AH_SUM, com_HN_BAC, com_HN_FUN, com_HN_SUM)


write.table(com , file = "./result/Fig5f_com.txt",sep = '\t',row.names = T)

```


# Fig 6? 条形图加显著性


## Fig 6e

```{r}
data = read.table("./data/Fig6g.txt",header = T, row.names = 1)
head(data)

data_1 <- filter(data, re == "1")
data_2 <- filter(data, re == "2")
```

```{r}
com_1 <- compare_means( ratio ~ treatment, data = data_1, method = "wilcox.test", paired=FALSE)
com_t1 <- compare_means( ratio ~ treatment, data = data_1, method = "t.test", paired=FALSE)
com_2 <- compare_means( ratio ~ treatment, data = data_2, method = "wilcox.test", paired=FALSE)
com_t2 <- compare_means( ratio ~ treatment, data = data_2, method = "t.test", paired=FALSE)
head(com_1)
head(com_t1)
head(com_2)
head(com_t2)

com <- rbind(com_1, com_t1, com_2, com_t2)


write.table(com , file = "./result/Fig6_load_com.txt",sep = '\t',row.names = T)
```

```{r}
p1 = ggbarplot(data_1, x = "treatment", y = "ratio", add = "mean_se")+
  stat_compare_means(method = "t.test")  
p1
ggsave(paste("./result/Fig6-load-1.pdf", sep=""), p1, width = 3, height = 6)
```


```{r}
p2 = ggbarplot(data_2, x = "treatment", y = "ratio", add = "mean_se")+
  stat_compare_means(method = "t.test", label.y=0.65)  
p2
ggsave(paste("./result/Fig6-load-2.pdf", sep=""), p2, width = 3, height = 6)
```

## Fig 5a

```{r}
load <- read.csv("data/Fig5f_sample.csv", header = T)

data_AH <- filter(load, Site == "AH")
data_HN <- filter(load, Site == "HN")
data_AH_BAC <- filter(data_AH, Micro == "bac")
data_AH_FUN <- filter(data_AH, Micro == "fungi")
data_AH_SUM <- filter(data_AH, Micro == "bacfun")

data_HN_BAC <- filter(data_HN, Micro == "bac")
data_HN_FUN <- filter(data_HN, Micro == "fungi")
data_HN_SUM <- filter(data_HN, Micro == "bacfun")
```


```{r}
# wilcox.test
com_AH_BAC <- compare_means( load ~ Type, data = data_AH_BAC, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
com_AH_FUN <- compare_means( load ~ Type, data = data_AH_FUN, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
com_AH_SUM <- compare_means( load ~ Type, data = data_AH_SUM, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")

com_HN_BAC <- compare_means( load ~ Type, data = data_HN_BAC, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
com_HN_FUN <- compare_means( load ~ Type, data = data_HN_FUN, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
com_HN_SUM <- compare_means( load ~ Type, data = data_HN_SUM, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")


com <- rbind(com_AH_BAC, com_AH_FUN, com_AH_SUM, com_HN_BAC, com_HN_FUN, com_HN_SUM)
rownames(com)<-c("AHMH63BAC","AHWYJBAC","AHMH63FUN","AHWYJFUN","AHMH63SUM","AHWYJSUM","HNMH63BAC","HNWYJBAC","HNMH63FUN","HNWYJFUN","HNMH63SUM","HNWYJSUM")

write.table(com , file = "./result/Fig5a_hn_ah_com.txt",sep = '\t',row.names = T)

```


```{r}
load_mean <- read.csv("data/Fig5f.csv", header = T)

data_AH_mean <- filter(load_mean, Site == "AH")

p4 <- ggplot(data_AH_mean , aes(x= Type, y = Mean, fill = Micro )) + 
  geom_bar(stat = "identity", width=0.7) + 
  geom_errorbar(aes(ymin=Mean2-Error, ymax=Mean2+Error), width=.1) +
  labs(x="Group", y="Quantitative kingdom abundance (QA)") +
  facet_wrap(~Genotype, ncol = 2) +
  scale_fill_manual(values = c("#fdffab","#a8e6cf"))+
  theme_bw()
p4

ggsave(paste("./result/Fig5A_ah.pdf", sep=""), p4, width = 4, height = 3)

```





