---
title: "Figure R-Script"
author: "Qin"
date: "2018/12/3"
output: html_document
---

```{r warning=FALSE, message=FALSE}
rm(list=ls()) 

library(ggplot2)
library(ggpubr)
library(dplyr)
library(tidyr)
library(broom)
library(plyr)
library(scales)
library(reshape2)
library(pheatmap)
```

## Fig 2a

```{r}
spike <- read.csv("data/Fig2a-glm.csv", header = T)

mod2 <- glm(counts ~ log2, family = poisson(link = "log"), data = spike)

p2 <- ggplot(spike, aes(log2, counts, color = Dilution)) +
  geom_point(size = 2.5) +
  theme_bw() +
  scale_y_continuous(limits = c(0, 12000)) +
  geom_smooth(method = "glm", size = 0.8, colour = "grey10")+
  labs(x="spike-in amount (log2 copies/reaction)", y="spike-in read counts") 

p2

cor.test(spike$log2,spike$counts,method="pearson")

lm.fit1 <- lm(spike$counts~ spike$log2)
coef(lm.fit1)


```

## Fig 2b

```{r}
## 读取数据集
data1 <- read.csv("data/Fig2b-bac-nospike-group2.csv", header = T)
colnames(data1)[1] = "bacteria"

data2 <- gather(data1, key = replicate , value = count, `sample01`:`sample05`)

## 作图
p <- ggplot(data2, aes(bacteria, count))+
  geom_boxplot(aes(fill = bacteria), na.rm = TRUE) +
  facet_wrap(~spike, ncol = 5) +
  scale_fill_manual(values = c("#ff8364", "#fdb87d", "#ffe8d5", "#fbd685","#7fa99b", 
                               "#d5eeff", "#87e0ff", "#53c7f0", "#1d97c1"))+
  labs(x="Bacteria", y="Count (%)")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0)) 
p

```



## Fig 2c - Fig 2f

```{r}
bac_ra <- read.csv("data/Fig2-bar-ra.csv", header = T)
table_bac_ra_r <- gather(bac_ra,  key = sample , value = count, `sample01`:`sample05`)
table_bac_ra <- table_bac_ra_r
table_bac_ra$bacteria <- factor(table_bac_ra_r$bacteria)
table_bac_ra$group <- factor(table_bac_ra_r$group)
E0520_bac_ra <- filter(table_bac_ra, spike == "E0520")
group1_E0520_bac_ra <- filter(E0520_bac_ra , group == "1")
group2_E0520_bac_ra <- filter(E0520_bac_ra , group == "2")
group3_E0520_bac_ra <- filter(E0520_bac_ra , group == "3")


bac_aa <- read.csv("data/Fig2-bar-aa.csv", header = T)
table_bac_aa_r <- gather(bac_aa,  key = sample , value = count, `sample01`:`sample05`)
table_bac_aa <- table_bac_aa_r
table_bac_aa$bacteria <- factor(table_bac_aa_r$bacteria)
table_bac_aa$group <- factor(table_bac_aa_r$group)
E0520_bac_aa <- filter(table_bac_aa, spike == "E0520")
group1_E0520_bac_aa <- filter(E0520_bac_aa, group == "1")
group2_E0520_bac_aa <- filter(E0520_bac_aa, group == "2")
group3_E0520_bac_aa <- filter(E0520_bac_aa, group == "3")

Fig2c_ra_g1g2 <- rbind(group1_E0520_bac_ra, group2_E0520_bac_ra)
Fig2d_aa_g1g2 <- rbind(group1_E0520_bac_aa, group2_E0520_bac_aa)
Fig2e_ra_g1g3 <- rbind(group1_E0520_bac_ra, group3_E0520_bac_ra)
Fig2f_aa_g1g3 <- rbind(group1_E0520_bac_aa, group3_E0520_bac_aa)
```


```{r}
Fig2c <- ggplot(Fig2c_ra_g1g2) +
  geom_boxplot(aes(x = bacteria, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#ffa07a"))+
  geom_line(aes(x = bacteria, y = mean, group = group, color = group), na.rm = TRUE) +
  labs(x="Bacteria", y="Relative abundance (%)")  +
  scale_x_discrete(limits=c("Act-101","Act-135","Act-140","Bac-186","Fir-11","Pro-1203","Pro-1204","Pro-670","Pro-672"))+
  scale_color_manual(values=c("#9acd32","#ffa07a"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
Fig2c



Fig2d <- ggplot(Fig2d_aa_g1g2) +
  geom_boxplot(aes(x = bacteria, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#ffa07a"))+
  geom_line(aes(x = bacteria, y = mean, group = group, color = group), na.rm = TRUE) +
  labs(x="Bacteria", y="Quantitative abundance (relative to plant)")  +
  scale_x_discrete(limits=c("Act-101","Act-135","Act-140","Bac-186","Fir-11","Pro-1203","Pro-1204","Pro-670","Pro-672"))+
  scale_color_manual(values=c("#9acd32","#ffa07a"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
Fig2d


Fig2e <- ggplot(Fig2e_ra_g1g3) +
  geom_boxplot(aes(x = bacteria, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#87cefa"))+
  geom_line(aes(x = bacteria, y = mean, group = group, color = group), na.rm = TRUE) +
  labs(x="Bacteria", y="Relative abundance (%)")  +
  scale_x_discrete(limits=c("Act-101","Act-135","Act-140","Bac-186","Fir-11","Pro-1203","Pro-1204","Pro-670","Pro-672"))+
  scale_color_manual(values=c("#9acd32","#87cefa"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
Fig2e


Fig2f <- ggplot(Fig2f_aa_g1g3) +
  geom_boxplot(aes(x = bacteria, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#87cefa"))+
  geom_line(aes(x = bacteria, y = mean, group = group, color = group), na.rm = TRUE) +
  labs(x="Bacteria", y="Quantitative abundance (relative to plant)")  +
  scale_x_discrete(limits=c("Act-101","Act-135","Act-140","Bac-186","Fir-11","Pro-1203","Pro-1204","Pro-670","Pro-672"))+
  scale_color_manual(values=c("#9acd32","#87cefa"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
Fig2f

```

## Fig 2g

```{r}
## bac ra_aa error

spike <- read.csv("data/Fig2e-bac-error.csv", header = T)
x <- c(0, 1, 1.3)
y <- c(0, 1, 1.3)
df <- data.frame(x=x, y=y)

bacplot <- ggplot(df, aes(x, y)) +
  geom_line() +
  geom_point(data = spike, aes(x = error_RA, y = error_AA, color = Group.2), na.rm = TRUE) + 
  theme_bw() +  
  scale_x_continuous(limits = c(0, 1.3)) + 
  scale_y_continuous(limits = c(0, 1.3)) + 
  labs(x="RA error", y="AA error") 
bacplot


```

## Fig 3a

```{r}
spike <- read.csv("data/Fig3a-glm.csv", header = T)
# log2

mod2 <- glm(counts ~ log2, family = poisson(link = "log"), data = spike)

p2 <- ggplot(spike, aes(log2, counts, color = Dilution)) +
  geom_point(size = 2.5) +
  theme_bw() +
  scale_y_continuous(limits = c(0, 10000)) +
  geom_smooth(method = "glm", size = 0.8, colour = "grey10")+
  labs(x="spike-in amount (log2 copies/reaction)", y="spike-in read counts") 

p2


cor.test(spike$log2,spike$counts,method="pearson")

lm.fit2 <- lm(spike$counts~ spike$log2)
coef(lm.fit2)

#ggsave(paste("result/Fig3a-glm-log2.pdf", sep=""), p2, width = 7, height = 6)


```


## Fig 3c - Fig 3f

```{r}
fun_ra <- read.csv("data/Fig3-fun-ra.csv", header = T)
table_fun_ra_r <- gather(fun_ra,  key = sample , value = count, `sample01`:`sample05`)
table_fun_ra <- table_fun_ra_r
table_fun_ra$fungi <- factor(table_fun_ra_r$fungi)
table_fun_ra$group <- factor(table_fun_ra_r$group)
E0520_fun_ra <- filter(table_fun_ra, spike == "E0520")
group1_E0520_fun_ra <- filter(E0520_fun_ra , group == "1")
group2_E0520_fun_ra <- filter(E0520_fun_ra , group == "2")
group3_E0520_fun_ra <- filter(E0520_fun_ra , group == "3")

fun_aa <- read.csv("data/Fig3-fun-aa.csv", header = T)
table_fun_aa_r <- gather(fun_aa,  key = sample , value = count, `sample01`:`sample05`)
table_fun_aa <- table_fun_aa_r
table_fun_aa$fungi <- factor(table_fun_aa_r$fungi)
table_fun_aa$group <- factor(table_fun_aa_r$group)
E0520_fun_aa <- filter(table_fun_aa, spike == "E0520")
group1_E0520_fun_aa <- filter(E0520_fun_aa, group == "1")
group2_E0520_fun_aa <- filter(E0520_fun_aa, group == "2")
group3_E0520_fun_aa <- filter(E0520_fun_aa, group == "3")

Fig3c_ra_g1g2 <- rbind(group1_E0520_fun_ra, group2_E0520_fun_ra)
Fig3d_aa_g1g2 <- rbind(group1_E0520_fun_aa, group2_E0520_fun_aa)
Fig3e_ra_g1g3 <- rbind(group1_E0520_fun_ra, group3_E0520_fun_ra)
Fig3f_aa_g1g3 <- rbind(group1_E0520_fun_aa, group3_E0520_fun_aa)
```



```{r}
Fig3c <- ggplot(Fig3c_ra_g1g2) +
  geom_boxplot(aes(x = fungi, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#ffa07a"))+
  geom_line(aes(x = fungi, y = mean, group = group, color = group), na.rm = TRUE) +
  labs(x="Fungi", y="Relative abundance (%)")  +
  scale_x_discrete(limits=c("Basi-AF78","Asco-AF1","Asco-AF105"))+
  scale_color_manual(values=c("#9acd32","#ffa07a"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
Fig3c



Fig3d <- ggplot(Fig3d_aa_g1g2) +
  geom_boxplot(aes(x = fungi, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#ffa07a"))+
  geom_line(aes(x = fungi, y = mean, group = group, color = group), na.rm = TRUE) +
  labs(x="Fungi", y="Quantitative abundance (relative to plant)")  +
  scale_x_discrete(limits=c("Basi-AF78","Asco-AF1","Asco-AF105"))+
  scale_color_manual(values=c("#9acd32","#ffa07a"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
Fig3d

Fig3e <- ggplot(Fig3e_ra_g1g3) +
  geom_boxplot(aes(x = fungi, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#87cefa"))+
  geom_line(aes(x = fungi, y = mean, group = group, color = group), na.rm = TRUE) +
  labs(x="Fungi", y="Relative abundance (%)")  +
  scale_x_discrete(limits=c("Basi-AF78","Asco-AF1","Asco-AF105"))+
  scale_color_manual(values=c("#9acd32","#87cefa"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
Fig3e

Fig3f <- ggplot(Fig3f_aa_g1g3) +
  geom_boxplot(aes(x = fungi, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#87cefa"))+
  geom_line(aes(x = fungi, y = mean, group = group, color = group), na.rm = TRUE) +
  labs(x="Fungi", y="Quantitative abundance (relative to plant)")  +
  scale_x_discrete(limits=c("Basi-AF78","Asco-AF1","Asco-AF105"))+
  scale_color_manual(values=c("#9acd32","#87cefa"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
Fig3f
```

## Fig 3g

```{r}
## fun ra_aa error

spike2 <- read.csv("data/Fig3e-fun-error.csv", header = T)

funplot <- ggplot(df, aes(x, y)) +
  geom_line() +
  geom_point(data = spike2, aes(x = RAerror, y = AAerror, color = Group.2), na.rm = TRUE) + 
  theme_bw() +  
  scale_x_continuous(limits = c(0, 1.3)) + 
  scale_y_continuous(limits = c(0, 1.3)) + 
  labs(x="Fungi RA error", y="Fungi AA error") 
funplot
```


# Fig 4a

```{r}
bac <- read.csv("data/Fig4a-lm-bac.csv", header = T)
fun <- read.csv("data/Fig4a-lm-fun.csv", header = T)

## Bacteria E05-E00
data_e05_bac <- dplyr::select(bac, OTUID, E05_bac, E00_bac)

x1 <- data_e05_bac$E05_bac
y1 <- data_e05_bac$E00_bac

cor.test(x1,y1,method="pearson")
lm.fit1 <- lm(y1~0+x1)
coef(lm.fit1)

plot(data_e05_bac$E05_bac,data_e05_bac$E00_bac,
     xlab ="OTU reads (%) Unamended root DNA", 
     ylab ="OTU reads (%) spiked root DNA")

abline(lm.fit1)
```

## Fig 4b

```{r}
## Fungi E05-E00
data_e05_fun <- dplyr::select(fun, OTUID, E05_fun, E00_fun)

x4 <- data_e05_fun$E05_fun
y4 <- data_e05_fun$E00_fun

cor.test(x4,y4,method="pearson")
lm.fit4 <- lm(y4~0+x4)
coef(lm.fit4)

plot(data_e05_fun$E05_fun,data_e05_fun$E00_fun,pch=2,
     xlab ="OTU reads (%) Unamended root DNA", 
     ylab ="OTU reads (%) spiked root DNA")

abline(lm.fit4)
```

## Fig 4c - Fig 4d

```{r}
bac <- read.csv("data/Fig4c-bac-all.csv")
fun <- read.csv("data/Fig4c-fun-all.csv")
fun2<- read.csv("data/Fig4c-fun-point.csv")

bac <- read.csv("data/Fig4c-bac-all.csv")
fun <- read.csv("data/Fig4c-fun-all.csv")
fun2<- read.csv("data/Fig4c-fun-point.csv")

## E05-BAC-RA

t1 <- dplyr::select(bac, Bac, E05_RA_ONE, E05_RA_TWO)

bac05ra <- gather(t1, key = variable , value = count, `E05_RA_ONE`:`E05_RA_TWO`)

p1 = ggplot(bac05ra, aes(x=variable, y = count, fill = Bac )) + 
  geom_bar(stat = "identity",position="fill", width=0.7)+ 
  scale_fill_manual(values = c("#ff8364", "#fbd685", 
                               "#7fa99b", "#f6f6e9", "#1d97c1"))+
  scale_y_continuous(labels = scales::percent) + 
  xlab("Groups")+
  ylab("Relative Abundance (%)")+ 
  theme_classic()
p1

## E05-BAC-QA

t4 <- dplyr::select(bac, Bac, E05_QA_ONE, E05_QA_TWO)

bac05qa <- gather(t4, key = variable , value = count, `E05_QA_ONE`:`E05_QA_TWO`)

p4 = ggplot(bac05qa, aes(x=variable, y = count, fill = Bac )) + 
  geom_bar(stat = "identity", width=0.7) + 
  scale_fill_manual(values = c("#ff8364", "#fbd685", 
                               "#7fa99b", "#f6f6e9", "#1d97c1"))+
  xlab("Groups")+
  ylab("Quantitative Abundance (relative to host plant)")+ 
  theme_classic()
p4

```

## Fig 4e - Fig 4f

```{r}
## E05-FUN-RA

f1 <- dplyr::select(fun, FUN, E05_RA_ONE, E05_RA_TWO)

fun05ra <- gather(f1, key = variable , value = count, `E05_RA_ONE`:`E05_RA_TWO`)

fp1 = ggplot(fun05ra, aes(x=variable, y = count, fill = FUN )) + 
  geom_bar(stat = "identity",position="fill", width=0.7)+ 
  scale_fill_manual(values = c("#8ea6b4", "#f8d5f0","#89a4c7"))+
  scale_y_continuous(labels = scales::percent) + 
  xlab("Groups")+
  ylab("Relative Abundance (%)")+ 
  theme_classic()
fp1

## E05-FUN-QA

f3 <- dplyr::select(fun, FUN, E05_QA_ONE, E05_QA_TWO)

fun05qa <- gather(f3, key = variable , value = count, `E05_QA_ONE`:`E05_QA_TWO`)

fp3 = ggplot(fun05qa, aes(x=variable, y = count, fill = FUN )) + 
  geom_bar(stat = "identity", width=0.7) + 
  scale_fill_manual(values = c("#8ea6b4", "#f8d5f0","#89a4c7"))+
  xlab("Groups")+
  ylab("Quantitative Abundance (relative to host plant)")+ 
  theme_classic()
fp3

```


## Fig 5a

```{r}
load <- read.csv("data/Fig5f_sample.csv", header = T)

data_AH <- filter(load, Site == "AH")
data_HN <- filter(load, Site == "HN")
data_AH_BAC <- filter(data_AH, Micro == "bac")
data_AH_FUN <- filter(data_AH, Micro == "fungi")
data_AH_SUM <- filter(data_AH, Micro == "bacfun")

data_HN_BAC <- filter(data_HN, Micro == "bac")
data_HN_FUN <- filter(data_HN, Micro == "fungi")
data_HN_SUM <- filter(data_HN, Micro == "bacfun")
```


```{r}
# wilcox.test
com_AH_BAC <- compare_means( load ~ Type, data = data_AH_BAC, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
com_AH_FUN <- compare_means( load ~ Type, data = data_AH_FUN, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
com_AH_SUM <- compare_means( load ~ Type, data = data_AH_SUM, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")

com_HN_BAC <- compare_means( load ~ Type, data = data_HN_BAC, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
com_HN_FUN <- compare_means( load ~ Type, data = data_HN_FUN, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")
com_HN_SUM <- compare_means( load ~ Type, data = data_HN_SUM, method = "wilcox.test", paired=FALSE,  group.by = "Genotype")


com <- rbind(com_AH_BAC, com_AH_FUN, com_AH_SUM, com_HN_BAC, com_HN_FUN, com_HN_SUM)
rownames(com)<-c("AHMH63BAC","AHWYJBAC","AHMH63FUN","AHWYJFUN","AHMH63SUM","AHWYJSUM","HNMH63BAC","HNWYJBAC","HNMH63FUN","HNWYJFUN","HNMH63SUM","HNWYJSUM")

```


```{r}
load_mean <- read.csv("data/Fig5f.csv", header = T)

data_HN_mean <- filter(load_mean, Site == "HN")

p4 <- ggplot(data_HN_mean , aes(x= Type, y = Mean, fill = Micro )) + 
  geom_bar(stat = "identity", width=0.7) + 
  geom_errorbar(aes(ymin=Mean2-Error, ymax=Mean2+Error), width=.1) +
  labs(x="Group", y="Quantitative kingdom abundance (QA)") +
  facet_wrap(~Genotype, ncol = 2) +
  scale_fill_manual(values = c("#fdffab","#a8e6cf"))+
  theme_bw()
p4
```

## Fig 5b

```{r}
data5c = read.table("./data/Fig5c_new.txt",header = T, row.names = 1)
head(data5c)
data5c_stat  = read.table("./data/Fig5c_new_stat.txt",header = T, row.names = 1)
head(data5c_stat)
```

```{r}
com_5c_w <- compare_means( ratio ~ treatment, data = data5c, method = "wilcox.test", paired=FALSE,  group.by = "genotype")
com_5c_t <- compare_means( ratio ~ treatment, data = data5c, method = "t.test", paired=FALSE,  group.by = "genotype")
com_5c <- rbind(com_5c_w, com_5c_t)
head(com_5c)
```


```{r}
p = ggplot(data5c_stat, aes(x = treatment, y = radio_mean)) + 
  geom_bar(stat = "identity",fill = "white", colour = "black", width=0.7, na.rm = TRUE)+ 
  geom_errorbar(aes(ymin= radio_mean - radio_error, ymax= radio_mean + radio_error), width=.1) + 
  facet_wrap(~genotype)+
  xlab("Groups")+
  ylab("Ratio of bacteria to host plant")+
  theme_bw()
p

```

## Fig 5c

```{r}
data <- read.csv("data/Fig5c-heatmap-p.csv", header = T)

## HN 12个门

data_hn <- dplyr::select(data, Bacteria, starts_with("HN"))

all <- gather(data_hn, key = group , value = logFC, `HN_MH_RA`:`HN_WYJ_AA`)

p_hn <- ggplot(all, aes(group, Bacteria)) + 
  geom_tile(aes(fill = logFC),colour = "grey50") + 
  scale_fill_gradient2(low = "#6D9EC1",high = "sandybrown", midpoint = 0)+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))+
  scale_y_discrete(limits=c("Gammaproteobacteria","Deltaproteobacteria","Betaproteobacteria",
                            "Alphaproteobacteria","Verrucomicrobia","Spirochaetes","Nitrospirae",
                            "Ignavibacteriae","Firmicutes","Chloroflexi","Bacteroidetes","Actinobacteria",
                            "Acidobacteria"))+
  scale_x_discrete(limits=c("HN_MH_RA","HN_MH_AA","HN_WYJ_RA","HN_WYJ_AA"))

p_hn

```

## Fig 5e - Fig 5f
```{r}
data_ra <- read.csv("data/Fig5e-otu-bar-ra.csv", header = T)
data_aa <- read.csv("data/Fig5e-otu-bar-aa.csv", header = T)


## OTU16-RA
data2 <- filter(data_ra, OTUS == "OTU_16")

p2 <- ggplot(data2) +
  geom_boxplot(aes(x = Treatment, y = RA), width = 0.3, na.rm = TRUE) +
  geom_jitter(aes(x = Treatment, y = RA, color = Treatment), width = 0.08, na.rm = TRUE) +
  labs(x="Group_OTU_16", y="Relative genus abundance (RA) (‰)") +
  scale_colour_manual(values = c("goldenrod1", "deepskyblue")) +
  theme_bw()
p2


## OTU13-RA
data3 <- filter(data_ra, OTUS == "OTU_13")

p3 <- ggplot(data3) +
  geom_boxplot(aes(x = Treatment, y = RA), width = 0.3, na.rm = TRUE) +
  geom_jitter(aes(x = Treatment, y = RA, color = Treatment), width = 0.08, na.rm = TRUE) +
  labs(x="Group_OTU_13", y="Relative genus abundance (RA) (‰)") +
  scale_colour_manual(values = c("goldenrod1", "deepskyblue")) +
  theme_bw()
p3

## OTU16-AA

data5 <- filter(data_aa, OTUS == "OTU_16")

p5 <- ggplot(data5) +
  geom_boxplot(aes(x = Treatment, y = AA), width = 0.3, na.rm = TRUE) +
  geom_jitter(aes(x = Treatment, y = AA, color = Treatment), width = 0.08, na.rm = TRUE) +
  labs(x="Group_OTU_16", y="Quantitative genus abundance (QA)") +
  scale_colour_manual(values = c("goldenrod1", "deepskyblue")) +
  theme_bw()
p5


## OTU13-AA

data6 <- filter(data_aa, OTUS == "OTU_13")

p6 <- ggplot(data5) +
  geom_boxplot(aes(x = Treatment, y = AA), width = 0.3, na.rm = TRUE) +
  geom_jitter(aes(x = Treatment, y = AA, color = Treatment), width = 0.08, na.rm = TRUE) +
  labs(x="Group_OTU_13", y="Quantitative genus abundance (QA)") +
  scale_colour_manual(values = c("goldenrod1", "deepskyblue")) +
  theme_bw()
p6


```


