---
title: "otu-bar-test"
author: "Qin"
date: "2018/12/21"
output: html_document
---

```{r warning=FALSE, message=FALSE}
print(paste("Your working directory is in",getwd()))
rm(list=ls()) 

library(ggplot2)
library(ggpubr)
library(dplyr)
```

### 海南MH63

```{r}
data <- read.table("./data/Fig-20181221-otubar-test.txt", header = T)
```

```{r}
data_en_over <- filter(data, Type == "enriched_overlap")
data_en_over_dry <- filter(data_en_over, Treatment == "dry")
data_en_over_wet <- filter(data_en_over, Treatment == "wet")
```

```{r}
data_en_over_dry  <- arrange(data_en_over_dry, desc(RA)) # decrease sort
data_en_over_dry$OTUID=factor(data_en_over_dry$OTUID,levels = data_en_over_dry$OTUID)
data_en_over_wet  <- arrange(data_en_over_wet, desc(RA)) # decrease sort
data_en_over_wet$OTUID=factor(data_en_over_wet$OTUID,levels = data_en_over_wet$OTUID)
data_en_over_merge <- rbind(data_en_over_dry, data_en_over_wet)
head(data_en_over_merge)
```


```{r}
p = ggplot(data_en_over_merge, aes(x = OTUID, y = RA, fill = Treatment)) + 
  geom_bar(stat="identity", position=position_dodge(),width=0.7, na.rm = TRUE)+
  scale_fill_manual(values=c("goldenrod1", "deepskyblue"))+ 
  xlab("OTUID")+
  ylab("Relative abundance (%)")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0, size = 7)) + 
  ggtitle("BacHnMH63dry_BacHnMH63wet_enriched_overlap")+ 
  theme(legend.justification=c(1,1), legend.position=c(1,1))+ 
  scale_y_continuous(breaks=seq(0, 30, 4))
p
ggsave(paste("result/20181221-otubar-BacHnMH63dry_wet_enriched_overlap.pdf", sep=""), p, width = 6, height = 4)
```


```{r}
data_en_aa <- filter(data, Type == "enriched_AA")
data_en_aa_dry <- filter(data_en_aa, Treatment == "dry")
data_en_aa_wet <- filter(data_en_aa, Treatment == "wet")
```

```{r}
data_en_aa_dry  <- arrange(data_en_aa_dry, desc(RA)) # decrease sort
data_en_aa_dry$OTUID=factor(data_en_aa_dry$OTUID,levels = data_en_aa_dry$OTUID)
data_en_aa_wet  <- arrange(data_en_aa_wet, desc(RA)) # decrease sort
data_en_aa_wet$OTUID=factor(data_en_aa_wet$OTUID,levels = data_en_aa_wet$OTUID)
data_en_aa_merge <- rbind(data_en_aa_dry, data_en_aa_wet)
head(data_en_aa_merge)
```


```{r}
p = ggplot(data_en_aa_merge, aes(x = OTUID, y = RA, fill = Treatment)) + 
  geom_bar(stat="identity", position=position_dodge(),width=0.7, na.rm = TRUE)+
  scale_fill_manual(values=c("goldenrod1", "deepskyblue"))+ 
  xlab("OTUID")+
  ylab("Relative abundance(%)")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0, size = 7)) + 
  ggtitle("BacHnMH63dry_BacHnMH63wet_enriched_AA")+ 
  theme(legend.justification=c(1,1), legend.position=c(1,1))+ 
  scale_y_continuous(breaks=seq(0, 5, 1))
p

ggsave(paste("result/20181221-otubar-BacHnMH63dry_wet_enriched_AA.pdf", sep=""), p, width = 6, height = 4)
```



```{r}
data_de_over <- filter(data, Type == "depleted_overlap")
data_de_over_dry <- filter(data_de_over, Treatment == "dry")
data_de_over_wet <- filter(data_de_over, Treatment == "wet")
```

```{r}
data_de_over_dry  <- arrange(data_de_over_dry, desc(RA)) # decrease sort
data_de_over_dry$OTUID=factor(data_de_over_dry$OTUID,levels = data_de_over_dry$OTUID)
data_de_over_wet  <- arrange(data_de_over_wet, desc(RA)) # decrease sort
data_de_over_wet$OTUID=factor(data_de_over_wet$OTUID,levels = data_de_over_wet$OTUID)
data_de_over_merge <- rbind(data_de_over_wet, data_de_over_dry)
head(data_de_over_merge)
```


```{r}
p = ggplot(data_de_over_merge, aes(x = OTUID, y = RA, fill = Treatment)) + 
  geom_bar(stat="identity", position=position_dodge(),width=0.7, na.rm = TRUE)+
  scale_fill_manual(values=c("goldenrod1", "deepskyblue"))+ 
  xlab("OTUID")+
  ylab("Relative abundance(%)")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0, size = 7)) + 
  ggtitle("BacHnMH63dry_BacHnMH63wet_depleted_overlap")+ 
  theme(legend.justification=c(1,1), legend.position=c(1,1))+ 
  scale_y_continuous(breaks=seq(0, 5, 0.5))
p

ggsave(paste("result/20181221-otubar-BacHnMH63dry_wet_depleted_overlap.pdf", sep=""), p, width = 6, height = 4)
```



```{r}
data_de_aa <- filter(data, Type == "depleted_AA")
data_de_aa_dry <- filter(data_de_aa, Treatment == "dry")
data_de_aa_wet <- filter(data_de_aa, Treatment == "wet")
```

```{r}
data_de_aa_dry  <- arrange(data_de_aa_dry, desc(RA)) # decrease sort
data_de_aa_dry$OTUID=factor(data_de_aa_dry$OTUID,levels = data_de_aa_dry$OTUID)
data_de_aa_wet  <- arrange(data_de_aa_wet, desc(RA)) # decrease sort
data_de_aa_wet$OTUID=factor(data_de_aa_wet$OTUID,levels = data_de_aa_wet$OTUID)
data_de_aa_merge <- rbind(data_de_aa_wet, data_de_aa_dry)
head(data_de_aa_merge)
```


```{r}
p = ggplot(data_de_aa_merge, aes(x = OTUID, y = RA, fill = Treatment)) + 
  geom_bar(stat="identity", position=position_dodge(),width=0.7, na.rm = TRUE)+
  scale_fill_manual(values=c("goldenrod1", "deepskyblue"))+ 
  xlab("OTUID")+
  ylab("Relative abundance(%)")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0, size = 7)) + 
  ggtitle("BacHnMH63dry_BacHnMH63wet_depleted_AA")+ 
  theme(legend.justification=c(1,1), legend.position=c(1,1))+ 
  scale_y_continuous(breaks=seq(0, 5, 0.01))
p

ggsave(paste("result/20181221-otubar-BacHnMH63dry_wet_depleted_AA.pdf", sep=""), p, width = 2, height = 4)
```


```{r}
data_de_ra <- filter(data, Type == "depleted_RA")
data_de_ra_dry <- filter(data_de_ra, Treatment == "dry")
data_de_ra_wet <- filter(data_de_ra, Treatment == "wet")
```

```{r}
data_de_ra_dry  <- arrange(data_de_ra_dry, desc(RA)) # decrease sort
data_de_ra_dry$OTUID=factor(data_de_ra_dry$OTUID,levels = data_de_ra_dry$OTUID)
data_de_ra_wet  <- arrange(data_de_ra_wet, desc(RA)) # decrease sort
data_de_ra_wet$OTUID=factor(data_de_ra_wet$OTUID,levels = data_de_ra_wet$OTUID)
data_de_ra_merge <- rbind(data_de_ra_wet, data_de_ra_dry)
head(data_de_ra_merge)
```


```{r}
p = ggplot(data_de_ra_merge, aes(x = OTUID, y = RA, fill = Treatment)) + 
  geom_bar(stat="identity", position=position_dodge(),width=0.7, na.rm = TRUE)+
  scale_fill_manual(values=c("goldenrod1", "deepskyblue"))+ 
  xlab("OTUID")+
  ylab("Relative abundance(%)")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0, size = 7)) + 
  ggtitle("BacHnMH63dry_BacHnMH63wet_depleted_ra")+ 
  theme(legend.justification=c(1,1), legend.position=c(1,1))+ 
  scale_y_continuous(breaks=seq(0, 5, 1))
p

ggsave(paste("result/20181221-otubar-BacHnMH63dry_wet_depleted_ra.pdf", sep=""), p, width = 5, height = 4)
```



### 海南WYJ

```{r}
data2 <- read.table("./data/Fig-20181221-otubar-test-hnwyj.txt", header = T)
```

```{r}
data_en_over <- filter(data2, Type == "enriched_overlap")
data_en_over_dry <- filter(data_en_over, Treatment == "dry")
data_en_over_wet <- filter(data_en_over, Treatment == "wet")
```

```{r}
data_en_over_dry  <- arrange(data_en_over_dry, desc(RA)) # decrease sort
data_en_over_dry$OTUID=factor(data_en_over_dry$OTUID,levels = data_en_over_dry$OTUID)
data_en_over_wet  <- arrange(data_en_over_wet, desc(RA)) # decrease sort
data_en_over_wet$OTUID=factor(data_en_over_wet$OTUID,levels = data_en_over_wet$OTUID)
data_en_over_merge <- rbind(data_en_over_dry, data_en_over_wet)
head(data_en_over_merge)
```


```{r}
p = ggplot(data_en_over_merge, aes(x = OTUID, y = RA, fill = Treatment)) + 
  geom_bar(stat="identity", position=position_dodge(),width=0.7, na.rm = TRUE)+
  scale_fill_manual(values=c("goldenrod1", "deepskyblue"))+ 
  xlab("OTUID")+
  ylab("Relative abundance (%)")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0, size = 7)) + 
  ggtitle("BacHnWYJ7DEP1dry_BacHnWYJ7DEP1wet_enriched_overlap")+ 
  theme(legend.justification=c(1,1), legend.position=c(1,1))+ 
  scale_y_continuous(breaks=seq(0, 20, 3))
p
ggsave(paste("result/20181221-otubar-BacHnWYJ7DEP1dry_wet_enriched_overlap.pdf", sep=""), p, width = 6, height = 4)
```





```{r}
data_en_aa <- filter(data2, Type == "enriched_AA")
data_en_aa_dry <- filter(data_en_aa, Treatment == "dry")
data_en_aa_wet <- filter(data_en_aa, Treatment == "wet")
```

```{r}
data_en_aa_dry  <- arrange(data_en_aa_dry, desc(RA)) # decrease sort
data_en_aa_dry$OTUID=factor(data_en_aa_dry$OTUID,levels = data_en_aa_dry$OTUID)
data_en_aa_wet  <- arrange(data_en_aa_wet, desc(RA)) # decrease sort
data_en_aa_wet$OTUID=factor(data_en_aa_wet$OTUID,levels = data_en_aa_wet$OTUID)
data_en_aa_merge <- rbind(data_en_aa_dry, data_en_aa_wet)
head(data_en_aa_merge)
```


```{r}
p = ggplot(data_en_aa_merge, aes(x = OTUID, y = RA, fill = Treatment)) + 
  geom_bar(stat="identity", position=position_dodge(),width=0.7, na.rm = TRUE)+
  scale_fill_manual(values=c("goldenrod1", "deepskyblue"))+ 
  xlab("OTUID")+
  ylab("Relative abundance(%)")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0, size = 7)) + 
  ggtitle("BacHnWYJ7DEP1dry_BacHnWYJ7DEP1wet_enriched_AA")+ 
  theme(legend.justification=c(1,1), legend.position=c(1,1))+ 
  scale_y_continuous(breaks=seq(0, 5, 1))
p

ggsave(paste("result/20181221-otubar-BacHnWYJ7DEP1dry_wet_enriched_AA.pdf", sep=""), p, width = 7, height = 4)
```


```{r}
data_de_over <- filter(data2, Type == "depleted_overlap")
data_de_over_dry <- filter(data_de_over, Treatment == "dry")
data_de_over_wet <- filter(data_de_over, Treatment == "wet")
```

```{r}
data_de_over_dry  <- arrange(data_de_over_dry, desc(RA)) # decrease sort
data_de_over_dry$OTUID=factor(data_de_over_dry$OTUID,levels = data_de_over_dry$OTUID)
data_de_over_wet  <- arrange(data_de_over_wet, desc(RA)) # decrease sort
data_de_over_wet$OTUID=factor(data_de_over_wet$OTUID,levels = data_de_over_wet$OTUID)
data_de_over_merge <- rbind(data_de_over_wet, data_de_over_dry)
head(data_de_over_merge)
```


```{r}
p = ggplot(data_de_over_merge, aes(x = OTUID, y = RA, fill = Treatment)) + 
  geom_bar(stat="identity", position=position_dodge(),width=0.7, na.rm = TRUE)+
  scale_fill_manual(values=c("goldenrod1", "deepskyblue"))+ 
  xlab("OTUID")+
  ylab("Relative abundance(%)")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0, size = 7)) + 
  ggtitle("BacHnWYJ7DEP1dry_BacHnWYJ7DEP1wet_depleted_overlap")+ 
  theme(legend.justification=c(1,1), legend.position=c(1,1))+ 
  scale_y_continuous(breaks=seq(0, 10, 1))
p

ggsave(paste("result/20181221-otubar-BacHnWYJ7DEP1dry_wet_depleted_overlap.pdf", sep=""), p, width = 7, height = 4)
```


```{r}
data_de_aa <- filter(data2, Type == "depleted_AA")
data_de_aa_dry <- filter(data_de_aa, Treatment == "dry")
data_de_aa_wet <- filter(data_de_aa, Treatment == "wet")
```

```{r}
data_de_aa_dry  <- arrange(data_de_aa_dry, desc(RA)) # decrease sort
data_de_aa_dry$OTUID=factor(data_de_aa_dry$OTUID,levels = data_de_aa_dry$OTUID)
data_de_aa_wet  <- arrange(data_de_aa_wet, desc(RA)) # decrease sort
data_de_aa_wet$OTUID=factor(data_de_aa_wet$OTUID,levels = data_de_aa_wet$OTUID)
data_de_aa_merge <- rbind(data_de_aa_wet, data_de_aa_dry)
head(data_de_aa_merge)
```


```{r}
p = ggplot(data_de_aa_merge, aes(x = OTUID, y = RA, fill = Treatment)) + 
  geom_bar(stat="identity", position=position_dodge(),width=0.7, na.rm = TRUE)+
  scale_fill_manual(values=c("goldenrod1", "deepskyblue"))+ 
  xlab("OTUID")+
  ylab("Relative abundance(%)")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0, size = 7)) + 
  ggtitle("BacHnWYJ7DEP1dry_BacHnWYJ7DEP1wet_depleted_AA")+ 
  theme(legend.justification=c(1,1), legend.position=c(1,1))+ 
  scale_y_continuous(breaks=seq(0, 5, 0.002))
p

ggsave(paste("result/20181221-otubar-BacHnWYJ7DEP1dry_wet_depleted_AA.pdf", sep=""), p, width = 2, height = 4)
```



```{r}
data_de_ra <- filter(data2, Type == "depleted_RA")
data_de_ra_dry <- filter(data_de_ra, Treatment == "dry")
data_de_ra_wet <- filter(data_de_ra, Treatment == "wet")
```

```{r}
data_de_ra_dry  <- arrange(data_de_ra_dry, desc(RA)) # decrease sort
data_de_ra_dry$OTUID=factor(data_de_ra_dry$OTUID,levels = data_de_ra_dry$OTUID)
data_de_ra_wet  <- arrange(data_de_ra_wet, desc(RA)) # decrease sort
data_de_ra_wet$OTUID=factor(data_de_ra_wet$OTUID,levels = data_de_ra_wet$OTUID)
data_de_ra_merge <- rbind(data_de_ra_wet, data_de_ra_dry)
head(data_de_ra_merge)
```


```{r}
p = ggplot(data_de_ra_merge, aes(x = OTUID, y = RA, fill = Treatment)) + 
  geom_bar(stat="identity", position=position_dodge(),width=0.7, na.rm = TRUE)+
  scale_fill_manual(values=c("goldenrod1", "deepskyblue"))+ 
  xlab("OTUID")+
  ylab("Relative abundance(%)")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0, size = 7)) + 
  ggtitle("BacHnWYJ7DEP1dry_BacHnWYJ7DEP1wet_depleted_RA")+ 
  theme(legend.justification=c(1,1), legend.position=c(1,1))+ 
  scale_y_continuous(breaks=seq(0, 5, 1))
p

ggsave(paste("result/20181221-otubar-BacHnWYJ7DEP1dry_wet_depleted_RA.pdf", sep=""), p, width = 7, height = 4)
```



















