---
title: "Figure S1 - S9"
author: "Qin Yuan"
date: "2019/4/1"
output: html_document
---

```{r warning=FALSE, message=FALSE}
rm(list=ls()) 

library(ggplot2)
library(ggpubr)
library(dplyr)
library(tidyr)
```

## Fig S1

```{r}
data1 <- read.table("data/Fig2_bac_mock_spike_g1g2.txt", header = T)
data1G <- gather(data1, key = replicate , value = count, `sample01`:`sample05`)

G1 <- filter(data1G, Group =="1")
G2 <- filter(data1G, Group =="2")
G3 <- filter(data1G, Group =="3")

bac_ra <- read.csv("data/Fig2c-bar-ra.csv", header = T)
table_bac_ra_r <- gather(bac_ra,  key = sample , value = count, `sample01`:`sample04`)
table_bac_ra <- table_bac_ra_r
table_bac_ra$bacteria <- factor(table_bac_ra_r$bacteria)
table_bac_ra$group <- factor(table_bac_ra_r$group)

table_bac_aa <- rbind(G1,G2)
table_bac_aa$bacteria <- factor(table_bac_aa$bacteria)
table_bac_aa$group <- factor(table_bac_aa$group)

E05_bac_ra <- filter(table_bac_ra, spike == "E05")
E55_bac_ra <- filter(table_bac_ra, spike == "E55")
E04_bac_ra <- filter(table_bac_ra, spike == "E04")
FigS3S4_bac_ra <- rbind(E05_bac_ra, E55_bac_ra, E04_bac_ra)

group1_FigS3S4_bac_ra <- filter(FigS3S4_bac_ra , group == "1:01:01")
group2_FigS3S4_bac_ra <- filter(FigS3S4_bac_ra , group == "2:02:02")

E05_bac_aa <- filter(table_bac_aa, spike == "E05")
E55_bac_aa <- filter(table_bac_aa, spike == "E55")
E04_bac_aa <- filter(table_bac_aa, spike == "E04")
FigS3S4_bac_aa <- rbind(E05_bac_aa, E55_bac_aa, E04_bac_aa)

group1_FigS3S4_bac_aa <- filter(FigS3S4_bac_aa , group == "1:01:01")
group2_FigS3S4_bac_aa <- filter(FigS3S4_bac_aa , group == "2:02:02")

FigS3_ra_g1g2 <- rbind(group1_FigS3S4_bac_ra, group2_FigS3S4_bac_ra)
FigS3_aa_g1g2 <- rbind(group1_FigS3S4_bac_aa, group2_FigS3S4_bac_aa)

FigS3_ra_g1g2$spike <- factor(FigS3_ra_g1g2$spike,levels=c("E05","E55", "E04"))
FigS3_aa_g1g2$spike <- factor(FigS3_aa_g1g2$spike,levels=c("E05","E55", "E04"))
```


```{r}
FigS3_ra <- ggplot(FigS3_ra_g1g2) +
  geom_boxplot(aes(x = bacteria, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#ffa07a"))+
  geom_line(aes(x = bacteria, y = mean, group = group, color = group), na.rm = TRUE) +
  facet_wrap(~spike, ncol = 3, as.table = TRUE) +
  labs(x="Bacteria", y="Relative abundance (%)")  +
  scale_x_discrete(limits=c("Act-101","Act-135","Act-140","Bac-186","Fir-11","Pro-1203","Pro-1204","Pro-670","Pro-672"))+
  scale_color_manual(values=c("#9acd32","#ffa07a"))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
FigS3_ra

# ggsave(paste("result/FigS1-ra.pdf", sep=""), FigS3_ra, width = 9, height = 5)
# ggsave(paste("result/FigS1-ra.png", sep=""), FigS3_ra, width = 9, height = 5)

FigS3_aa <- ggplot(FigS3_aa_g1g2) +
  geom_boxplot(aes(x = bacteria, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#ffa07a"))+
  geom_line(aes(x = bacteria, y = mean, group = group, color = group), na.rm = TRUE) +
  facet_wrap(~spike, ncol = 3, as.table = TRUE) +
  labs(x="Bacteria", y="Quantitative abundance (relative to plant)")  +
  scale_x_discrete(limits=c("Act-101","Act-135","Act-140","Bac-186","Fir-11","Pro-1203","Pro-1204","Pro-670","Pro-672"))+
  scale_color_manual(values=c("#9acd32","#ffa07a"))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
FigS3_aa

# ggsave(paste("result/FigS1_aa.pdf", sep=""), FigS3_aa, width = 9, height = 5)
# ggsave(paste("result/FigS1_aa.png", sep=""), FigS3_aa, width = 9, height = 5)

```


## Fig S2


```{r}
data1 <- read.table("data/Fig2_bac_mock_spike_g1g3.txt", header = T)
data1G <- gather(data1, key = replicate , value = count, `sample01`:`sample05`)

G1 <- filter(data1G, Group =="1")
G2 <- filter(data1G, Group =="2")
G3 <- filter(data1G, Group =="3")
bac_ra <- read.csv("data/Fig2e-bar-ra.csv", header = T)
table_bac_ra_r <- gather(bac_ra,  key = sample , value = count, `sample01`:`sample05`)
table_bac_ra <- table_bac_ra_r
table_bac_ra$bacteria <- factor(table_bac_ra_r$bacteria)
table_bac_ra$group <- factor(table_bac_ra_r$group)

table_bac_aa <- rbind(G1,G3)
table_bac_aa$bacteria <- factor(table_bac_aa$bacteria)
table_bac_aa$group <- factor(table_bac_aa$group)

E05_bac_ra <- filter(table_bac_ra, spike == "E05")
E55_bac_ra <- filter(table_bac_ra, spike == "E55")
E04_bac_ra <- filter(table_bac_ra, spike == "E04")
FigS3S4_bac_ra <- rbind(E05_bac_ra, E55_bac_ra, E04_bac_ra)

group1_FigS3S4_bac_ra <- filter(FigS3S4_bac_ra , group == "1:01:01")
group3_FigS3S4_bac_ra <- filter(FigS3S4_bac_ra , group == "2:02:01")

E05_bac_aa <- filter(table_bac_aa, spike == "E05")
E55_bac_aa <- filter(table_bac_aa, spike == "E55")
E04_bac_aa <- filter(table_bac_aa, spike == "E04")
FigS3S4_bac_aa <- rbind(E05_bac_aa, E55_bac_aa, E04_bac_aa)

group1_FigS3S4_bac_aa <- filter(FigS3S4_bac_aa , group == "1:01:01")
group3_FigS3S4_bac_aa <- filter(FigS3S4_bac_aa , group == "2:02:01")

FigS4_ra_g1g3 <- rbind(group1_FigS3S4_bac_ra, group3_FigS3S4_bac_ra)
FigS4_aa_g1g3 <- rbind(group1_FigS3S4_bac_aa, group3_FigS3S4_bac_aa)

FigS4_ra_g1g3$spike <- factor(FigS4_ra_g1g3$spike,levels=c("E05","E55", "E04"))
FigS4_aa_g1g3$spike <- factor(FigS4_aa_g1g3$spike,levels=c("E05","E55", "E04"))
```


```{r}
 
FigS4_ra <- ggplot(FigS4_ra_g1g3) +
  geom_boxplot(aes(x = bacteria, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#87cefa"))+
  geom_line(aes(x = bacteria, y = mean, group = group, color = group), na.rm = TRUE) +
  facet_wrap(~spike, ncol = 3, as.table = TRUE) +
  labs(x="Bacteria", y="Relative abundance (%)")  +
  scale_x_discrete(limits=c("Act-101","Act-135","Act-140","Bac-186","Fir-11","Pro-1203","Pro-1204","Pro-670","Pro-672"))+
  scale_color_manual(values=c("#9acd32","#87cefa"))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
FigS4_ra

# ggsave(paste("result/FigS2_ra.pdf", sep=""), FigS4_ra, width = 9, height = 5)
# ggsave(paste("result/FigS2_ra.png", sep=""), FigS4_ra, width = 9, height = 5)

FigS4_aa <- ggplot(FigS4_aa_g1g3) +
  geom_boxplot(aes(x = bacteria, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#87cefa"))+
  geom_line(aes(x = bacteria, y = mean, group = group, color = group), na.rm = TRUE) +
  facet_wrap(~spike, ncol = 3, as.table = TRUE) +
  labs(x="Bacteria", y="Quantitative abundance (relative to plant)")  +
  scale_x_discrete(limits=c("Act-101","Act-135","Act-140","Bac-186","Fir-11","Pro-1203","Pro-1204","Pro-670","Pro-672"))+
  scale_color_manual(values=c("#9acd32","#87cefa"))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
FigS4_aa
# 
# ggsave(paste("result/FigS2_aa.pdf", sep=""), FigS4_aa, width = 9, height = 5)
# ggsave(paste("result/FigS2_aa.png", sep=""), FigS4_aa, width = 9, height = 5)

```



## Fig S3

```{r}
rm(list=ls()) 

data1 <- read.table("data/Fig3_fun_mock_spike.txt", header = T)
data1G <- gather(data1, key = replicate , value = count, `sample01`:`sample05`)

G1 <- filter(data1G, Group =="1")
G2 <- filter(data1G, Group =="2")
G3 <- filter(data1G, Group =="3")

fun_ra <- read.csv("data/Fig3c-bar-ra.csv", header = T)
table_fun_ra_r <- gather(fun_ra,  key = sample , value = count, `sample01`:`sample04`)
table_fun_ra <- table_fun_ra_r
table_fun_ra$fungi <- factor(table_fun_ra_r$fungi)
table_fun_ra$group <- factor(table_fun_ra_r$group)

table_fun_aa <- rbind(G1,G2)
table_fun_aa$fungi <- factor(table_fun_aa$fungi)
table_fun_aa$group <- factor(table_fun_aa$group)

E05_fun_ra <- filter(table_fun_ra, spike == "E05")
E55_fun_ra <- filter(table_fun_ra, spike == "E055")
E04_fun_ra <- filter(table_fun_ra, spike == "E04")
FigS3S4_fun_ra <- rbind(E05_fun_ra, E55_fun_ra, E04_fun_ra)

group1_FigS3S4_fun_ra <- filter(FigS3S4_fun_ra , group =="2:02:02" )
group2_FigS3S4_fun_ra <- filter(FigS3S4_fun_ra , group =="1:01:01")

E05_fun_aa <- filter(table_fun_aa, spike == "E05")
E55_fun_aa <- filter(table_fun_aa, spike == "E55")
E04_fun_aa <- filter(table_fun_aa, spike == "E04")
FigS3S4_fun_aa <- rbind(E05_fun_aa, E55_fun_aa, E04_fun_aa)

group1_FigS3S4_fun_aa <- filter(FigS3S4_fun_aa , group =="2:02:02")
group2_FigS3S4_fun_aa <- filter(FigS3S4_fun_aa , group =="1:01:01")

FigS6_ra_g1g2 <- rbind(group1_FigS3S4_fun_ra, group2_FigS3S4_fun_ra)
FigS6_aa_g1g2 <- rbind(group1_FigS3S4_fun_aa, group2_FigS3S4_fun_aa)

FigS6_ra_g1g2$spike <- factor(FigS6_ra_g1g2$spike,levels=c("E05","E055", "E04"))
FigS6_aa_g1g2$spike <- factor(FigS6_aa_g1g2$spike,levels=c("E05","E55", "E04"))
```


```{r}
FigS6_ra <- ggplot(FigS6_ra_g1g2) +
  geom_boxplot(aes(x = fungi, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#ffa07a"))+
  geom_line(aes(x = fungi, y = mean, group = group, color = group), na.rm = TRUE) +
  facet_wrap(~spike, ncol = 3, as.table = TRUE) +
  labs(x="Fungi", y="Relative abundance (%)")  +
  scale_x_discrete(limits=c("Basi-AF78","Asco-AF1","Asco-AF105"))+
  scale_color_manual(values=c("#9acd32","#ffa07a"))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
FigS6_ra

# ggsave(paste("result/FigS3-ra.pdf", sep=""), FigS6_ra, width = 9, height = 5)
# ggsave(paste("result/FigS3-ra.png", sep=""), FigS6_ra, width = 9, height = 5)

FigS6_aa <- ggplot(FigS6_aa_g1g2) +
  geom_boxplot(aes(x = fungi, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#ffa07a"))+
  geom_line(aes(x = fungi, y = mean, group = group, color = group), na.rm = TRUE) +
  facet_wrap(~spike, ncol = 3, as.table = TRUE) +
  labs(x="Fungi", y="Quantitative abundance (relative to plant)")  +
  scale_x_discrete(limits=c("Basi-AF78","Asco-AF1","Asco-AF105"))+
  scale_color_manual(values=c("#9acd32","#ffa07a"))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
FigS6_aa

# ggsave(paste("result/FigS3_aa.pdf", sep=""), FigS6_aa, width = 9, height = 5)
# ggsave(paste("result/FigS3_aa.png", sep=""), FigS6_aa, width = 9, height = 5)

```



## Fig S4

```{r}
fun_ra <- read.csv("data/Fig3e-bar-ra.csv", header = T)
table_fun_ra_r <- gather(fun_ra,  key = sample , value = count, `sample01`:`sample04`)
table_fun_ra <- table_fun_ra_r
table_fun_ra$fungi <- factor(table_fun_ra_r$fungi)
table_fun_ra$group <- factor(table_fun_ra_r$group)

table_fun_aa <- rbind(G2,G3)
table_fun_aa$fungi <- factor(table_fun_aa$fungi)
table_fun_aa$group <- factor(table_fun_aa$group)

E05_fun_ra <- filter(table_fun_ra, spike == "E05")
E55_fun_ra <- filter(table_fun_ra, spike == "E055")
E04_fun_ra <- filter(table_fun_ra, spike == "E04")
FigS3S4_fun_ra <- rbind(E05_fun_ra, E55_fun_ra, E04_fun_ra)

group1_FigS3S4_fun_ra <- filter(FigS3S4_fun_ra , group == "1:01:01")
group3_FigS3S4_fun_ra <- filter(FigS3S4_fun_ra , group == "2:02:01")

E05_fun_aa <- filter(table_fun_aa, spike == "E05")
E55_fun_aa <- filter(table_fun_aa, spike == "E55")
E04_fun_aa <- filter(table_fun_aa, spike == "E04")
FigS3S4_fun_aa <- rbind(E05_fun_aa, E55_fun_aa, E04_fun_aa)

group1_FigS3S4_fun_aa <- filter(FigS3S4_fun_aa , group == "1:01:01")
group3_FigS3S4_fun_aa <- filter(FigS3S4_fun_aa , group == "2:02:01")

FigS7_ra_g1g3 <- rbind(group1_FigS3S4_fun_ra, group3_FigS3S4_fun_ra)
FigS7_aa_g1g3 <- rbind(group1_FigS3S4_fun_aa, group3_FigS3S4_fun_aa)

FigS7_ra_g1g3$spike <- factor(FigS7_ra_g1g3$spike,levels=c("E05","E055", "E04"))
FigS7_aa_g1g3$spike <- factor(FigS7_aa_g1g3$spike,levels=c("E05","E55", "E04"))
```

```{r}
FigS7_ra <- ggplot(FigS7_ra_g1g3) +
  geom_boxplot(aes(x = fungi, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#87cefa"))+
  geom_line(aes(x = fungi, y = mean, group = group, color = group), na.rm = TRUE) +
  facet_wrap(~spike, ncol = 3, as.table = TRUE) +
  labs(x="Fungi", y="Relative abundance (%)")  +
  scale_x_discrete(limits=c("Basi-AF78","Asco-AF1","Asco-AF105"))+
  scale_color_manual(values=c("#9acd32","#87cefa"))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
FigS7_ra
# 
# ggsave(paste("result/FigS4_ra.pdf", sep=""), FigS7_ra, width = 9, height = 5)
# ggsave(paste("result/FigS4_ra.png", sep=""), FigS7_ra, width = 9, height = 5)

FigS7_aa <- ggplot(FigS7_aa_g1g3) +
  geom_boxplot(aes(x = fungi, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#87cefa"))+
  geom_line(aes(x = fungi, y = mean, group = group, color = group), na.rm = TRUE) +
  facet_wrap(~spike, ncol = 3, as.table = TRUE) +
  labs(x="Fungi", y="Quantitative abundance (relative to plant)")  +
  scale_x_discrete(limits=c("Basi-AF78","Asco-AF1","Asco-AF105"))+
  scale_color_manual(values=c("#9acd32","#87cefa"))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
FigS7_aa
# 
# ggsave(paste("result/FigS4_aa.pdf", sep=""), FigS7_aa, width = 9, height = 5)
# ggsave(paste("result/FigS4_aa.png", sep=""), FigS7_aa, width = 9, height = 5)

```



## Fig S5


```{r}
bac <- read.csv("./data/20180807-fig4-lm-bac.csv", header = T)
fun <- read.csv("./data/20180807-fig4-lm-fun.csv", header = T)

## Bacteria E04-E00

data_e04_bac <- select(bac, OTUID, E04_bac, E00_bac)

x2 <- data_e04_bac$E04_bac
y2 <- data_e04_bac$E00_bac

cor.test(x2,y2,method="pearson")
lm.fit2 <-lm(y2~0+x2)
coef(lm.fit2)

plot(data_e04_bac$E04_bac,data_e04_bac$E00_bac,
     xlab ="OTU reads (%) Unamended root DNA", 
     ylab ="OTU reads (%) spiked root DNA")

abline(lm.fit2)


## Bacteria E03-E00

data_e03_bac <- select(bac, OTUID, E03_bac, E00_bac)

x3 <- data_e03_bac$E03_bac
y3 <- data_e03_bac$E00_bac

cor.test(x3,y3,method="pearson")
lm.fit3 <-lm(y3~0+x3)
coef(lm.fit3)

plot(data_e03_bac$E03_bac,data_e03_bac$E00_bac,
     xlab ="OTU reads (%) Unamended root DNA", 
     ylab ="OTU reads (%) spiked root DNA")

abline(lm.fit3)


## Fungi E03-E00

data_e03_fun <- select(fun, OTUID, E03_fun, E00_fun)

x6 <- data_e03_fun$E03_fun
y6 <- data_e03_fun$E00_fun

cor.test(x6,y6,method="pearson")
lm.fit6 <- lm(y6~0+x6)
coef(lm.fit6)

plot(data_e03_fun$E03_fun,data_e03_fun$E00_fun,pch=2,
     xlab ="OTU reads (%) Unamended root DNA", 
     ylab ="OTU reads (%) spiked root DNA")

abline(lm.fit6)

```


## Fig S7

```{r}
bac <- read.table("data/Fig4c_bac_aa_ra.txt", header=T, sep="\t")
fun <- read.table("data/Fig4_fun_aa_ra.txt", header=T, sep="\t")

## E04-BAC-RA

t2 <- dplyr::select(bac, Bac, E04_RA_Natural, E04_RA_Perturb)

bac04ra <- gather(t2, key = variable , value = count, `E04_RA_Natural`:`E04_RA_Perturb`)

p2 = ggplot(bac04ra, aes(x=variable, y = count, fill = Bac )) + 
  geom_bar(stat = "identity",position="fill", width=0.7)+ 
  scale_fill_manual(values = c("#ff8364", "#fbd685", 
                               "#7fa99b", "#f6f6e9", "#1d97c1"))+
  scale_y_continuous(labels = scales::percent) + 
  xlab("Groups")+
  ylab("Relative Abundance (%)")+ 
  theme_classic()
p2
# ggsave(paste("./result/FigS7_E04_RA.pdf", sep=""), p2 , width = 3.5, height = 3)
# ggsave(paste("./result/FigS7_E04_RA.png", sep=""), p2 , width = 3.5, height = 3)


## E03-BAC-RA

t3 <- dplyr::select(bac, Bac, E03_RA_Natural, E03_RA_Perturb)

bac03ra <- gather(t3, key = variable , value = count, `E03_RA_Natural`:`E03_RA_Perturb`)

p3 = ggplot(bac03ra, aes(x=variable, y = count, fill = Bac )) + 
  geom_bar(stat = "identity",position="fill", width=0.7)+ 
  scale_fill_manual(values = c("#ff8364", "#fbd685", 
                               "#7fa99b", "#f6f6e9", "#1d97c1"))+
  scale_y_continuous(labels = scales::percent) + 
  xlab("Groups")+
  ylab("Relative Abundance (%)")+ 
  theme_classic()
p3
# ggsave(paste("./result/FigS7_E03_RA.pdf", sep=""), p3 , width = 3.5, height = 3)
# ggsave(paste("./result/FigS7_E03_RA.png", sep=""), p3 , width = 3.5, height = 3)



## E04-BAC-QA

t5 <- dplyr::select(bac, Bac, E04_AA_Natural, E04_AA_Perturb)

bac04qa <- gather(t5, key = variable , value = count, `E04_AA_Natural`:`E04_AA_Perturb`)

p5 = ggplot(bac04qa, aes(x=variable, y = count, fill = Bac )) + 
  geom_bar(stat = "identity", width=0.7) + 
  scale_fill_manual(values = c("#ff8364", "#fbd685", 
                               "#7fa99b", "#f6f6e9", "#1d97c1"))+
  xlab("Groups")+
  ylab("Quantitative Abundance (relative to host plant)")+ 
  theme_classic()
p5
# ggsave(paste("./result/FigS7_E04_AA.pdf", sep=""), p5 , width = 3.5, height = 3)
# ggsave(paste("./result/FigS7_E04_AA.png", sep=""), p5 , width = 3.5, height = 3)


## E03-BAC-QA

t6 <- dplyr::select(bac, Bac, E03_AA_Natural, E03_AA_Perturb)

bac03qa <- gather(t6, key = variable , value = count, `E03_AA_Natural`:`E03_AA_Perturb`)

p6 = ggplot(bac03qa, aes(x=variable, y = count, fill = Bac )) + 
  geom_bar(stat = "identity", width=0.7) + 
  scale_fill_manual(values = c("#ff8364", "#fbd685", 
                               "#7fa99b", "#f6f6e9", "#1d97c1"))+
  xlab("Groups")+
  ylab("Quantitative Abundance (relative to host plant)")+ 
  theme_classic()
p6
# ggsave(paste("./result/FigS7_E03_AA.pdf", sep=""), p6 , width = 3.5, height = 3)
# ggsave(paste("./result/FigS7_E03_AA.png", sep=""), p6 , width = 3.5, height = 3)
 
```



## Fig S7  Fungi


```{r}
## E03-FUN-RA

f2 <- dplyr::select(fun, FUN, E03_RA_Natural, E03_RA_Perturb)

fun03ra <- gather(f2, key = variable , value = count, `E03_RA_Natural`:`E03_RA_Perturb`)

fp2 = ggplot(fun03ra, aes(x=variable, y = count, fill = FUN )) + 
  geom_bar(stat = "identity",position="fill", width=0.7)+ 
  scale_fill_manual(values = c("#8ea6b4", "#f8d5f0","#89a4c7"))+
  scale_y_continuous(labels = scales::percent) + 
  xlab("Groups")+
  ylab("Relative Abundance (%)")+ 
  theme_classic()
fp2
# ggsave(paste("./result/FigS7_E03_fun_RA.pdf", sep=""), fp2, width = 3.5, height = 3)
# ggsave(paste("./result/FigS7_E03_fun_RA.png", sep=""), fp2, width = 3.5, height = 3)

## E03-FUN-QA

f4 <-  dplyr::select(fun, FUN, E03_AA_Natural, E03_AA_Perturb)

fun03qa <- gather(f4, key = variable , value = count, `E03_AA_Natural`:`E03_AA_Perturb`)

fp4 = ggplot(fun03qa, aes(x=variable, y = count, fill = FUN )) + 
  geom_bar(stat = "identity", width=0.7) + 
  scale_fill_manual(values = c("#8ea6b4", "#f8d5f0","#89a4c7"))+
  xlab("Groups")+
  ylab("Quantitative Abundance (relative to host plant)")+ 
  theme_classic()
fp4

# ggsave(paste("./result/FigS7_E03_fun_AA.pdf", sep=""), fp4, width = 3.5, height = 3)
# ggsave(paste("./result/FigS7_E03_fun_AA.png", sep=""), fp4, width = 3.5, height = 3)
```

## Figure S8

```{r warning=FALSE, message=FALSE}
rm(list=ls()) 
source("plot_function.R")
# install.packages("ggpubr")
library(ggpubr)
library(vegan)
library(ggplot2)
library(multcomp)
library(ggsignif)
library("Biobase", quietly=T, warn.conflicts=F)
library("ggplot2", quietly=T, warn.conflicts=F)
library("gplots", quietly=T, warn.conflicts=F)
library("grid", quietly=T, warn.conflicts=F)
library("RColorBrewer", quietly=T, warn.conflicts=F)
library("reshape2", quietly=T, warn.conflicts=F)
```

```{r}
#####spike-in design in this batch #####################
spike <- c("BI-OS-11-3","BI-OS-12-4","BI-OS-10-2")

design = read.table("data/beta_wetdry/design.txt", header=T, row.names= 1, sep="\t") 

batch_group <- unique(design$site)               # plasmid id 
condition_group <- unique(design$Other)
geno_group <- unique(design$Genotype)                 # Concentration


#####RA AH
dist<- bray_curtis <- read.table("data/beta_wetdry/bray_curtis_otutab.txt", sep="\t", header=T, row.names = 1,check.names=F,stringsAsFactors = F)
 design$SampleID <- row.names(design)

design = design[rownames(design) %in% rownames(bray_curtis),]
id <- match(row.names(design[design$site %in% "Ah"&!design$Genotype %in% "MH63ZH",]),rownames(bray_curtis))

ah_bray_curtis <- bray_curtis[id,id]

```

```{r}
k <- 3
pcoa <- cmdscale(ah_bray_curtis, k=k, eig=T)

points <- pcoa$points
eig <- pcoa$eig
points <- as.data.frame(points)
colnames(points) <- c("x", "y","z")

points <- cbind(points, design[match(rownames(points), design$SampleID), ])
colors <- data.frame(group=geno_group,color=c(c_red, c_dark_brown,c_black,c_orange))
shapes <- data.frame(group=condition_group,shape=c(19, 0))


# plot PCo 1 and 2

p <- ggplot(points, aes(x=x, y=y, color=Genotype,shape=Other)) +
  geom_point(alpha=.7, size=5) +
  scale_colour_manual(values=as.character(colors$color)) +
  scale_shape_manual(values=shapes$shape) +
  labs(x=paste("PCoA 1 (", format(100 * eig[1] / sum(eig), digits=4), "%)", sep=""),
       y=paste("PCoA 2 (", format(100 * eig[2] / sum(eig), digits=4), "%)", sep="")) + 
  main_theme +
  theme(legend.position="top")
p

```

```{r}
#### Hainan

design = design[rownames(design) %in% rownames(bray_curtis),]
id <- match(row.names(design[design$site %in% "Hn"&!design$Genotype %in% "MH63ZH",]),rownames(bray_curtis))

hn_bray_curtis <- bray_curtis[id,id]

k <- 3
pcoa <- cmdscale(hn_bray_curtis, k=k, eig=T)

points <- pcoa$points
eig <- pcoa$eig
points <- as.data.frame(points)
colnames(points) <- c("x", "y","z")

points <- cbind(points, design[match(rownames(points), design$SampleID), ])
colors <- data.frame(group=geno_group, color=c(c_red, c_dark_brown,c_black,c_orange))
shapes <- data.frame(group=condition_group, shape=c(19, 0))
```

```{r}
# plot PCo 1 and 2

p <- ggplot(points, aes(x=x, y=y, color=Genotype,shape=Other)) +
  geom_point(alpha=.7, size=5) +
  scale_colour_manual(values=as.character(colors$color)) +
  scale_shape_manual(values=shapes$shape) +
  labs(x=paste("PCoA 1 (", format(100 * eig[1] / sum(eig), digits=4), "%)", sep=""),
       y=paste("PCoA 2 (", format(100 * eig[2] / sum(eig), digits=4), "%)", sep="")) + 
  main_theme +
  theme(legend.position="top")
p
```

```{r}
## Fungi
design = read.table("data/beta_wetdry/design_fungi.txt", header=T, row.names= 1, sep="\t") 
design$SampleID <- row.names(design)

bray_curtis <- read.table("data/beta_wetdry/bray_curtis_otutab_1.txt", sep="\t", header=T, row.names = 1,check.names=F,stringsAsFactors = F)

```


```{r}
#### AnHui
design = design[rownames(design) %in% rownames(bray_curtis),]
id <- match(row.names(design[design$Site %in% "AnHui"&!design$Genotype %in% "MH63ZH",]), rownames(bray_curtis) )

ah_bray_curtis <- bray_curtis[id,id]
design <- design[rownames(design) %in% rownames(ah_bray_curtis),]

geno_group <- unique(design$Genotype)                 # Concentration
condition_group <- unique(design$Condition)


#### Unconstrained ordination
# pcoa<-capscale(dis~10
k <- 3
pcoa <- cmdscale(ah_bray_curtis, k=k, eig=T)
# pcoa <- cmdscale(eulian, k=k, eig=T)
points <- pcoa$points
eig <- pcoa$eig
points <- as.data.frame(points)
colnames(points) <- c("x", "y","z")
# points$Concentration <- rep(c("One_fold_plant","Two_fold_plant","Fun_spike_perturbation"),each=3,4)

points <- cbind(points, design[match(rownames(points), design$SampleID), ])
points <- points[-nrow(points),]

colors <- data.frame(group=geno_group, color=c(c_red, c_dark_brown,c_black))

shapes <- data.frame(group=condition_group, shape=c(19, 0))

# plot PCo 1 and 2

p <- ggplot(points, aes(x=x, y=y, color=Genotype,shape=Condition)) +
  geom_point(alpha=.7, size=5) +
  scale_colour_manual(values=as.character(colors$color)) +
  scale_shape_manual(values=shapes$shape) +
  labs(x=paste("PCoA 1 (", format(100 * eig[1] / sum(eig), digits=4), "%)", sep=""),
       y=paste("PCoA 2 (", format(100 * eig[2] / sum(eig), digits=4), "%)", sep="")) + 
  main_theme +
  theme(legend.position="top")
p
```

```{r}
design = read.table("data/beta_wetdry/design_fungi.txt", header=T, row.names= 1, sep="\t") 
design$SampleID <- row.names(design)
design = design[rownames(design) %in% rownames(bray_curtis),]
id <- match(row.names(design[design$Site %in% "HaiNan"&!design$Genotype %in% "MH63ZH",]), rownames(bray_curtis))

ah_bray_curtis <- bray_curtis[id,id]
design <- design[rownames(design) %in% rownames(ah_bray_curtis),]

geno_group <- unique(design$Genotype)                 # Concentration
condition_group <- unique(design$Condition)

#### Unconstrained ordination
k <- 3
pcoa <- cmdscale(ah_bray_curtis, k=k, eig=T)
points <- pcoa$points
eig <- pcoa$eig
points <- as.data.frame(points)
colnames(points) <- c("x", "y","z")
points <- cbind(points, design[match(rownames(points), design$SampleID), ])
points <- points[-nrow(points),]
colors <- data.frame(group=geno_group,color=c(c_red, c_dark_brown,c_black))

shapes <- data.frame(group=condition_group,shape=c(19, 0))


# plot PCo 1 and 2

p <- ggplot(points, aes(x=x, y=y, color=Genotype,shape=Condition)) +
  geom_point(alpha=.7, size=5) +
  scale_colour_manual(values=as.character(colors$color)) +
  scale_shape_manual(values=shapes$shape) +
  labs(x=paste("PCoA 1 (", format(100 * eig[1] / sum(eig), digits=4), "%)", sep=""),
       y=paste("PCoA 2 (", format(100 * eig[2] / sum(eig), digits=4), "%)", sep="")) + 
  main_theme +
  theme(legend.position="top")
p

```

## Figure S9

```{r warning=FALSE, message=FALSE}
rm(list=ls()) 

library(ggplot2)
library(ggpubr)
library(dplyr)
library(tidyr)
```

```{r}
load_bac <- read.table("data/totalload_tab_bac_usearch.txt", header = T)
load_fun <- read.table("data/totalload_tab_fun_usearch.txt", header = T)
load <- rbind(load_bac, load_fun)

## Bacteria dataset

data_Ah_BAC <- filter(load_bac, site == "Ah")
data_Hn_BAC <- filter(load_bac, site == "Hn")
data_Ah_FUN <- filter(load_fun, site == "Ah")
data_Hn_FUN <- filter(load_fun, site == "Hn")
 
load_mean <- read.table("data/Fig5a_mean_usearch.txt", header = T)

data_Ah_mean <- filter(load_mean, Site == "Ah")

p1 <- ggplot(data_Ah_mean , aes(x= Type, y = Mean, fill = Micro )) + 
  geom_bar(stat = "identity", width=0.7) + 
  geom_errorbar(aes(ymin=Mean2-Error, ymax=Mean2+Error), width=.1) +
  labs(x="Group", y="Quantitative kingdom abundance (QA)") +
  facet_wrap(~Genotype, ncol = 2) +
  scale_fill_manual(values = c("#ffc785","darkseagreen3"))+
  theme_bw()
p1
# ggsave("./result/SFig9_totalload_Ah.pdf", p1, width = 5, height = 4)
# ggsave("./result/SFig9_totalload_Ah.png", p1, width = 5, height = 4)
```

```{r}
data <- read.csv("data/20180724-heatmap-p.csv", header = T)
data_ah <- dplyr::select(data, Bacteria, starts_with("AH"))

all2 <- gather(data_ah, key = group , value = logFC, `AH_MH_RA`:`AH_WYJ_AA`)

p_ah <- ggplot(all2, aes(group, Bacteria)) + 
  geom_tile(aes(fill = logFC),colour = "grey50") + 
  scale_fill_gradient2(low = "#6D9EC1",high = "sandybrown", midpoint = 0)+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))+
  scale_y_discrete(limits=c("Gammaproteobacteria","Deltaproteobacteria","Betaproteobacteria",
                            "Alphaproteobacteria","Verrucomicrobia","Spirochaetes","Nitrospirae",
                            "Firmicutes","Chloroflexi","Bacteroidetes","Actinobacteria",
                            "Acidobacteria"))+
  scale_x_discrete(limits=c("AH_MH_RA","AH_MH_AA","AH_WYJ_RA","AH_WYJ_AA"))
p_ah

```

