---
title: "Figure 2"
author: "Qin Yuan"
date: "2019/4/1"
output: html_document
---

```{r warning=FALSE, message=FALSE}
rm(list=ls()) 

library(ggplot2)
library(ggpubr)
library(dplyr)
library(tidyr)
library(broom)
library(plyr)
library(scales)
library(pheatmap)
library("reshape2", quietly=T, warn.conflicts=F)
library(ggalluvial)
```


## Fig 2a

```{r}

spike <- read.csv("data/Fig2a-glm-group1.csv", header = T)

mod1 <- glm(counts ~ log2, family = poisson(link = "log"), data = spike)

p1 <- ggplot(spike, aes(log2, counts))+
  geom_smooth(method = "glm", size = 0.8, colour = "grey10") +
  geom_point(size = 2.5, colour = "grey20") +
  theme_bw() +
  scale_y_continuous(limits = c(0, 13000)) +
  labs(x="spike-in amount (log2 copies/reaction)", y="spike-in read counts") 

p1
# 
# ggsave(paste("result/Fig2a-glm-group1-20190218.pdf", sep=""), p1, width = 6, height = 6)


cor.test(spike$log2,spike$counts,method="pearson")

lm.fit1 <- lm(spike$counts~ spike$log2)
coef(lm.fit1)

```
## Fig 2b

```{r}
data1 <- read.csv("data/Fig2b-group1.csv", header = T)

data1G <- gather(data1, key = replicate , value = count, `sample01`:`sample05`)


p1G <- ggplot(data1G, aes(bacteria, count))+
  geom_boxplot(aes(fill = bacteria), na.rm = TRUE) +
  facet_wrap(~spike, ncol = 5) +
  scale_fill_manual(values = c("#ff8364", "#fdb87d", "#ffe8d5", "#fbd685","#7fa99b", 
                               "#d5eeff", "#87e0ff", "#53c7f0", "#1d97c1"))+
  labs(x="Bacteria", y="Count (%)")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0)) 
p1G
# ggsave(paste("result/Fig2b-group1.pdf", sep=""), p1G, width = 8, height = 6)

```



## Fig 2c - Fig 2d

```{r}
bac_ra <- read.csv("data/Fig2c-bar-ra.csv", header = T)
table_bac_ra_r <- gather(bac_ra,  key = sample , value = count, `sample01`:`sample04`)
table_bac_ra <- table_bac_ra_r
table_bac_ra$bacteria <- factor(table_bac_ra_r$bacteria)
table_bac_ra$group <- factor(table_bac_ra_r$group)
E0520_bac_ra <- filter(table_bac_ra, spike == "E0520")
group1_E0520_bac_ra <- filter(E0520_bac_ra , group == "1:01:01")
group2_E0520_bac_ra <- filter(E0520_bac_ra , group == "2:02:02")


bac_aa <- read.csv("data/Fig2d-bar-aa.csv", header = T)
table_bac_aa_r <- gather(bac_aa,  key = sample , value = count, `sample01`:`sample04`)
table_bac_aa <- table_bac_aa_r
table_bac_aa$bacteria <- factor(table_bac_aa_r$bacteria)
table_bac_aa$group <- factor(table_bac_aa_r$group)
E0520_bac_aa <- filter(table_bac_aa, spike == "E0520")
group1_E0520_bac_aa <- filter(E0520_bac_aa, group == "1:01:01")
group2_E0520_bac_aa <- filter(E0520_bac_aa, group == "2:02:02")

Fig2c_ra_g1g2 <- rbind(group1_E0520_bac_ra, group2_E0520_bac_ra)
Fig2d_aa_g1g2 <- rbind(group1_E0520_bac_aa, group2_E0520_bac_aa)

```


```{r}
Fig2c <- ggplot(Fig2c_ra_g1g2) +
  geom_boxplot(aes(x = bacteria, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#ffa07a"))+
  geom_line(aes(x = bacteria, y = mean, group = group, color = group), na.rm = TRUE) +
  labs(x="Bacteria", y="Relative abundance (%)")  +
  scale_x_discrete(limits=c("Act-101","Act-135","Act-140","Bac-186","Fir-11","Pro-1203","Pro-1204","Pro-670","Pro-672"))+
  scale_color_manual(values=c("#9acd32","#ffa07a"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
Fig2c

#ggsave(paste("result/Fig2c-ra-g1g2-boxplot.pdf", sep=""), Fig2c, width = 7, height = 6)


Fig2d <- ggplot(Fig2d_aa_g1g2) +
  geom_boxplot(aes(x = bacteria, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#ffa07a"))+
  geom_line(aes(x = bacteria, y = mean, group = group, color = group), na.rm = TRUE) +
  labs(x="Bacteria", y="Quantitative abundance (relative to plant)")  +
  scale_x_discrete(limits=c("Act-101","Act-135","Act-140","Bac-186","Fir-11","Pro-1203","Pro-1204","Pro-670","Pro-672"))+
  scale_color_manual(values=c("#9acd32","#ffa07a"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
Fig2d
#ggsave(paste("result/Fig2d-aa-g1g2-boxplot.pdf", sep=""), Fig2d, width = 7, height = 6)

```


## Fig 2e - Fig 2f

```{r}
bac_ra <- read.csv("data/Fig2e-bar-ra.csv", header = T)
table_bac_ra_r <- gather(bac_ra,  key = sample , value = count, `sample01`:`sample05`)
table_bac_ra <- table_bac_ra_r
table_bac_ra$bacteria <- factor(table_bac_ra_r$bacteria)
table_bac_ra$group <- factor(table_bac_ra_r$group)
E0520_bac_ra <- filter(table_bac_ra, spike == "E0520")
group1_E0520_bac_ra <- filter(E0520_bac_ra , group == "1:01:01")
group3_E0520_bac_ra <- filter(E0520_bac_ra , group == "2:02:01")

bac_aa <- read.csv("data/Fig2f-bar-aa.csv", header = T)
table_bac_aa_r <- gather(bac_aa,  key = sample , value = count, `sample01`:`sample05`)
table_bac_aa <- table_bac_aa_r
table_bac_aa$bacteria <- factor(table_bac_aa_r$bacteria)
table_bac_aa$group <- factor(table_bac_aa_r$group)
E0520_bac_aa <- filter(table_bac_aa, spike == "E0520")
group1_E0520_bac_aa <- filter(E0520_bac_aa, group == "1:01:01")
group3_E0520_bac_aa <- filter(E0520_bac_aa, group == "2:02:01")

Fig2e_ra_g1g3 <- rbind(group1_E0520_bac_ra, group3_E0520_bac_ra)
Fig2f_aa_g1g3 <- rbind(group1_E0520_bac_aa, group3_E0520_bac_aa)
```



```{r}
Fig2e <- ggplot(Fig2e_ra_g1g3) +
  geom_boxplot(aes(x = bacteria, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#87cefa"))+
  geom_line(aes(x = bacteria, y = mean, group = group, color = group), na.rm = TRUE) +
  labs(x="Bacteria", y="Relative abundance (%)")  +
  scale_x_discrete(limits=c("Act-101","Act-135","Act-140","Bac-186","Fir-11","Pro-1203","Pro-1204","Pro-670","Pro-672"))+
  scale_color_manual(values=c("#9acd32","#87cefa"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
Fig2e
# ggsave(paste("result/Fig2e-ra-g1g3-boxplot.pdf", sep=""), Fig2e, width = 7, height = 6)


Fig2f <- ggplot(Fig2f_aa_g1g3) +
  geom_boxplot(aes(x = bacteria, y = count, fill = group), width = 0.3, na.rm = TRUE) +
  scale_fill_manual(values=c("#9acd32","#87cefa"))+
  geom_line(aes(x = bacteria, y = mean, group = group, color = group), na.rm = TRUE) +
  labs(x="Bacteria", y="Quantitative abundance (relative to plant)")  +
  scale_x_discrete(limits=c("Act-101","Act-135","Act-140","Bac-186","Fir-11","Pro-1203","Pro-1204","Pro-670","Pro-672"))+
  scale_color_manual(values=c("#9acd32","#87cefa"))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))
Fig2f
# ggsave(paste("result/Fig2f-aa-g1g3-boxplot.pdf", sep=""), Fig2f, width = 7, height = 6)

```

## Fig 2g

```{r}
## bac ra_aa error

spike <- read.csv("data/Fig2g-error.csv", header = T)
x <- c(0, 1, 1.3)
y <- c(0, 1, 1.3)
df <- data.frame(x=x, y=y)

bacplot <- ggplot(df, aes(x, y)) +
  geom_line() +
  geom_point(data = spike, aes(x = error_RA, y = error_AA, color = Spikeinamount), size = 2.5, na.rm = TRUE) + 
  theme_bw() +  
  scale_x_continuous(limits = c(0, 1.3)) + 
  scale_y_continuous(limits = c(0, 1.3)) + 
  labs(x="Bacteria RA error", y="Bacteria QA error")
bacplot

# ggsave(paste("result/Fig2g-error.pdf", sep=""), bacplot, width = 7, height = 6)

```