---
title: "Figure5"
author: "Qin Yuan"
date: "2019/4/1"
output: html_document
---


```{r warning=FALSE, message=FALSE}
rm(list=ls()) 

library(ggplot2)
library(ggpubr)
library(dplyr)
library(tidyr)
library(broom)
library(plyr)
library(scales)
library(pheatmap)
library("reshape2", quietly=T, warn.conflicts=F)
library(ggalluvial)
```

## Fig 5a

```{r}
load <- read.csv("data/Fig5f_sample.csv", header = T)

data_AH <- filter(load, Site == "AH")
data_HN <- filter(load, Site == "HN")
data_AH_BAC <- filter(data_AH, Micro == "bac")
data_AH_FUN <- filter(data_AH, Micro == "fungi")
data_AH_SUM <- filter(data_AH, Micro == "bacfun")

data_HN_BAC <- filter(data_HN, Micro == "bac")
data_HN_FUN <- filter(data_HN, Micro == "fungi")
data_HN_SUM <- filter(data_HN, Micro == "bacfun")
```




```{r}
load_mean <- read.csv("data/Fig5f.csv", header = T)

data_HN_mean <- filter(load_mean, Site == "HN")

p4 <- ggplot(data_HN_mean , aes(x= Type, y = Mean, fill = Micro )) + 
  geom_bar(stat = "identity", width=0.7) + 
  geom_errorbar(aes(ymin=Mean2-Error, ymax=Mean2+Error), width=.1) +
  labs(x="Group", y="Quantitative kingdom abundance (QA)") +
  facet_wrap(~Genotype, ncol = 2) +
  scale_fill_manual(values = c("#fdffab","#a8e6cf"))+
  theme_bw()
p4
```

## Fig 5b

```{r}
data5c = read.table("./data/Fig5c_new.txt",header = T, row.names = 1)
head(data5c)
data5c_stat  = read.table("./data/Fig5c_new_stat.txt",header = T, row.names = 1)
head(data5c_stat)
```

```{r}
com_5c_w <- compare_means( ratio ~ treatment, data = data5c, method = "wilcox.test", paired=FALSE,  group.by = "genotype")
com_5c_t <- compare_means( ratio ~ treatment, data = data5c, method = "t.test", paired=FALSE,  group.by = "genotype")
com_5c <- rbind(com_5c_w, com_5c_t)
head(com_5c)
```


```{r}
p = ggplot(data5c_stat, aes(x = treatment, y = radio_mean)) + 
  geom_bar(stat = "identity",fill = "white", colour = "black", width=0.7, na.rm = TRUE)+ 
  geom_errorbar(aes(ymin= radio_mean - radio_error, ymax= radio_mean + radio_error), width=.1) + 
  facet_wrap(~genotype)+
  xlab("Groups")+
  ylab("Ratio of bacteria to host plant")+
  theme_bw()
p

```

## Fig 5c

```{r}
corr <- read.table("data/Fig-0215-correlationplot.txt", header = T)

x1 <- corr$ratio
y1 <- corr$load

cor.test(x1,y1,method="pearson")
lm.fit1 <- lm(y1~0+x1)
coef(lm.fit1)

plot(corr$ratio,corr$load,
     xlab =" Ratios of microbial reads to host plant reads", 
     ylab ="Microbial load generated by Si-QAP")

abline(lm.fit1)


p <- ggplot(corr, aes(ratio, load)) +
  geom_point(size = 2.5) +
  theme_classic()+
  geom_smooth(method = "glm", size = 0.8, colour = "grey10")+
  labs(x="Ratios of microbial reads to host plant reads", y="Microbial load generated by Si-QAP") 

p
# 
# 
# ggsave(paste("result/Fig-0215-correlationplot.pdf", sep=""), p, width = 7, height = 6)

```

## Fig 5d

```{r}
data <- read.csv("data/Fig5c-heatmap-p.csv", header = T)

## HN

data_hn <- dplyr::select(data, Bacteria, starts_with("HN"))

all <- gather(data_hn, key = group , value = logFC, `HN_MH_RA`:`HN_WYJ_AA`)

p_hn <- ggplot(all, aes(group, Bacteria)) + 
  geom_tile(aes(fill = logFC),colour = "grey50") + 
  scale_fill_gradient2(low = "#6D9EC1",high = "sandybrown", midpoint = 0)+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))+
  scale_y_discrete(limits=c("Gammaproteobacteria","Deltaproteobacteria","Betaproteobacteria",
                            "Alphaproteobacteria","Verrucomicrobia","Spirochaetes","Nitrospirae",
                            "Ignavibacteriae","Firmicutes","Chloroflexi","Bacteroidetes","Actinobacteria",
                            "Acidobacteria"))+
  scale_x_discrete(limits=c("HN_MH_RA","HN_MH_AA","HN_WYJ_RA","HN_WYJ_AA"))

p_hn

```

## Fig 5f - Fig 5h
```{r}
data_ra <- read.csv("data/Fig5e-otu-bar-ra.csv", header = T)
data_aa <- read.csv("data/Fig5e-otu-bar-aa.csv", header = T)


## OTU16-RA
data2 <- filter(data_ra, OTUS == "OTU_16")

p2 <- ggplot(data2) +
  geom_boxplot(aes(x = Treatment, y = RA), width = 0.3, na.rm = TRUE) +
  geom_jitter(aes(x = Treatment, y = RA, color = Treatment), width = 0.08, na.rm = TRUE) +
  labs(x="Group_OTU_16", y="Relative genus abundance (RA) (‰)") +
  scale_colour_manual(values = c("goldenrod1", "deepskyblue")) +
  theme_bw()
p2

## OTU11-RA
data1 <- filter(data_ra, OTUS == "OTU_11")

p1 <- ggplot(data2) +
  geom_boxplot(aes(x = Treatment, y = RA), width = 0.3, na.rm = TRUE) +
  geom_jitter(aes(x = Treatment, y = RA, color = Treatment), width = 0.08, na.rm = TRUE) +
  labs(x="Group_OTU_11", y="Relative genus abundance (RA) (‰)") +
  scale_colour_manual(values = c("goldenrod1", "deepskyblue")) +
  theme_bw()
p1

## OTU13-RA
data3 <- filter(data_ra, OTUS == "OTU_13")

p3 <- ggplot(data3) +
  geom_boxplot(aes(x = Treatment, y = RA), width = 0.3, na.rm = TRUE) +
  geom_jitter(aes(x = Treatment, y = RA, color = Treatment), width = 0.08, na.rm = TRUE) +
  labs(x="Group_OTU_13", y="Relative genus abundance (RA) (‰)") +
  scale_colour_manual(values = c("goldenrod1", "deepskyblue")) +
  theme_bw()
p3

## OTU16-AA

data5 <- filter(data_aa, OTUS == "OTU_16")

p5 <- ggplot(data5) +
  geom_boxplot(aes(x = Treatment, y = AA), width = 0.3, na.rm = TRUE) +
  geom_jitter(aes(x = Treatment, y = AA, color = Treatment), width = 0.08, na.rm = TRUE) +
  labs(x="Group_OTU_16", y="Quantitative genus abundance (QA)") +
  scale_colour_manual(values = c("goldenrod1", "deepskyblue")) +
  theme_bw()
p5

## OTU16-AA

data4 <- filter(data_aa, OTUS == "OTU_11")

p4 <- ggplot(data4) +
  geom_boxplot(aes(x = Treatment, y = AA), width = 0.3, na.rm = TRUE) +
  geom_jitter(aes(x = Treatment, y = AA, color = Treatment), width = 0.08, na.rm = TRUE) +
  labs(x="Group_OTU_11", y="Quantitative genus abundance (QA)") +
  scale_colour_manual(values = c("goldenrod1", "deepskyblue")) +
  theme_bw()
p4

## OTU13-AA

data6 <- filter(data_aa, OTUS == "OTU_13")

p6 <- ggplot(data5) +
  geom_boxplot(aes(x = Treatment, y = AA), width = 0.3, na.rm = TRUE) +
  geom_jitter(aes(x = Treatment, y = AA, color = Treatment), width = 0.08, na.rm = TRUE) +
  labs(x="Group_OTU_13", y="Quantitative genus abundance (QA)") +
  scale_colour_manual(values = c("goldenrod1", "deepskyblue")) +
  theme_bw()
p6

```