---
title: "Figure 5. HA-QAP revealed microbial load increase in rice roots under drought stress. "
author: "Qin Yuan"
date: "2019/4/1"
output: html_document
---

```{r warning=FALSE, message=FALSE}
rm(list=ls())  
library(ggplot2)
library(ggpubr)
library(dplyr)
library(tidyr)
library(broom)
library(plyr)
library(scales)
library(pheatmap)
library("reshape2", quietly=T, warn.conflicts=F)
library(ggalluvial)
```


## Fig 5a

```{r}
load_bac <- read.table("data/totalload_tab_bac_usearch.txt", header = T)
load_fun <- read.table("data/totalload_tab_fun_usearch.txt", header = T)
load <- rbind(load_bac, load_fun)

## Bacteria dataset

data_Ah_BAC <- filter(load_bac, site == "Ah")
data_Hn_BAC <- filter(load_bac, site == "Hn")
data_Ah_FUN <- filter(load_fun, site == "Ah")
data_Hn_FUN <- filter(load_fun, site == "Hn")

```



```{r}
load_mean <- read.table("data/Fig5a_mean_usearch.txt", header = T)
data_Hn_mean <- filter(load_mean, Site == "Hn")

p1 <- ggplot(data_Hn_mean , aes(x= Type, y = Mean, fill = Micro )) + 
  geom_bar(stat = "identity", width=0.7) + 
  geom_errorbar(aes(ymin=Mean2-Error, ymax=Mean2+Error), width=.1) +
  labs(x="Group", y="Quantitative kingdom abundance (QA)") +
  facet_wrap(~Genotype, ncol = 2) +
  scale_fill_manual(values = c("#ffc785","darkseagreen3"))+
  theme_bw()
p1
# ggsave("./result/Fig5a_totalload_Hn.pdf", p1, width = 5, height = 4)
# ggsave("./result/Fig5a_totalload_Hn.png", p1, width = 5, height = 4)
```

## Fig5a totalload 

```{r}
load_bac <- read.table("data/totalload_tab_bac_usearch.txt", header = T)
load_fun <- read.table("data/totalload_tab_fun_usearch.txt", header = T)
load_micro <- read.table("data/totalload_tab_micro_usearch.txt", header = T)

######### ---bacteria--- ########

ah_total <- dplyr::filter(load_bac, site == "Ah")
hn_total <- dplyr::filter(load_bac, site == "Hn")

com_t <- compare_means( microbialload ~ Condition, data = ah_total, group.by = "Genotype",
                        method = "t.test" , paired = F)
# write.table(com_t, file = "./result/stat/totalload_ah_bac_com_ttest.txt",sep = '\t',row.names = T)

com_w <- compare_means( microbialload ~ Condition, data = ah_total, group.by = "Genotype",
                        method = "wilcox.test" , paired = F)
# write.table(com_w, file = "./result/stat/totalload_ah_bac_com_wilcoxtest.txt",sep = '\t',row.names = T)

p <- ggboxplot(ah_total, x="Condition", y = "microbialload", color = "Condition", facet.by = "Genotype",
               palette = "jco", add = "jitter")
p

p_ttest <- p + stat_compare_means(method = "t.test", label.x = 1.5)
p_ttest
p_wtest <- p + stat_compare_means(method = "wilcox.test", label.x = 1.5)
p_wtest

# ggsave(paste("./result/stat/totalload_ah_bac_com_ttest.pdf", sep=""), p_ttest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_ah_bac_com_ttest.png", sep=""), p_ttest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_ah_bac_com_wilcoxtest.pdf", sep=""), p_wtest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_ah_bac_com_wilcoxtest.png", sep=""), p_wtest, width = 6, height = 6)


com_t <- compare_means( microbialload ~ Condition, data = hn_total, group.by = "Genotype",
                        method = "t.test" , paired = F)
# write.table(com_t, file = "./result/stat/totalload_hn_bac_com_ttest.txt",sep = '\t',row.names = T)

com_w <- compare_means( microbialload ~ Condition, data = hn_total, group.by = "Genotype",
                        method = "wilcox.test" , paired = F)
# write.table(com_w, file = "./result/stat/totalload_hn_bac_com_wilcoxtest.txt",sep = '\t',row.names = T)

p <- ggboxplot(hn_total, x="Condition", y = "microbialload", color = "Condition", facet.by = "Genotype",
               palette = "jco", add = "jitter")
p

p_ttest <- p + stat_compare_means(method = "t.test", label.x = 1.5)
p_ttest
p_wtest <- p + stat_compare_means(method = "wilcox.test", label.x = 1.5)
p_wtest

# ggsave(paste("./result/stat/totalload_hn_bac_com_ttest.pdf", sep=""), p_ttest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_hn_bac_com_ttest.png", sep=""), p_ttest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_hn_bac_com_wilcoxtest.pdf", sep=""), p_wtest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_hn_bac_com_wilcoxtest.png", sep=""), p_wtest, width = 6, height = 6)

######### ---fungi--- ########

ah_total <- dplyr::filter(load_fun, site == "Ah")
hn_total <- dplyr::filter(load_fun, site == "Hn")

com_t <- compare_means( microbialload ~ Condition, data = ah_total, group.by = "Genotype",
                        method = "t.test" , paired = F)
# write.table(com_t, file = "./result/stat/totalload_ah_fun_com_ttest.txt",sep = '\t',row.names = T)

com_w <- compare_means( microbialload ~ Condition, data = ah_total, group.by = "Genotype",
                        method = "wilcox.test" , paired = F)
# write.table(com_w, file = "./result/stat/totalload_ah_fun_com_wilcoxtest.txt",sep = '\t',row.names = T)

p <- ggboxplot(ah_total, x="Condition", y = "microbialload", color = "Condition", facet.by = "Genotype",
               palette = "jco", add = "jitter")
p

p_ttest <- p + stat_compare_means(method = "t.test", label.x = 1.5)
p_ttest
p_wtest <- p + stat_compare_means(method = "wilcox.test", label.x = 1.5)
p_wtest

# ggsave(paste("./result/stat/totalload_ah_fun_com_ttest.pdf", sep=""), p_ttest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_ah_fun_com_ttest.png", sep=""), p_ttest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_ah_fun_com_wilcoxtest.pdf", sep=""), p_wtest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_ah_fun_com_wilcoxtest.png", sep=""), p_wtest, width = 6, height = 6)

com_t <- compare_means( microbialload ~ Condition, data = hn_total, group.by = "Genotype",
                        method = "t.test" , paired = F)
# write.table(com_t, file = "./result/stat/totalload_hn_fun_com_ttest.txt",sep = '\t',row.names = T)

com_w <- compare_means( microbialload ~ Condition, data = hn_total, group.by = "Genotype",
                        method = "wilcox.test" , paired = F)
# write.table(com_w, file = "./result/stat/totalload_hn_fun_com_wilcoxtest.txt",sep = '\t',row.names = T)

p <- ggboxplot(hn_total, x="Condition", y = "microbialload", color = "Condition", facet.by = "Genotype",
               palette = "jco", add = "jitter")
p

p_ttest <- p + stat_compare_means(method = "t.test", label.x = 1.5)
p_ttest
p_wtest <- p + stat_compare_means(method = "wilcox.test", label.x = 1.5)
p_wtest
# 
# ggsave(paste("./result/stat/totalload_hn_fun_com_ttest.pdf", sep=""), p_ttest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_hn_fun_com_ttest.png", sep=""), p_ttest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_hn_fun_com_wilcoxtest.pdf", sep=""), p_wtest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_hn_fun_com_wilcoxtest.png", sep=""), p_wtest, width = 6, height = 6)

######### ---micro--- ########

ah_total <- dplyr::filter(load_micro, site == "Ah")
hn_total <- dplyr::filter(load_micro, site == "Hn")
com_t <- compare_means( microbialload ~ Condition, data = ah_total, group.by = "Genotype",
                        method = "t.test" , paired = F)
# write.table(com_t, file = "./result/stat/totalload_ah_micro_com_ttest.txt",sep = '\t',row.names = T)

com_w <- compare_means( microbialload ~ Condition, data = ah_total, group.by = "Genotype",
                        method = "wilcox.test" , paired = F)
# write.table(com_w, file = "./result/stat/totalload_ah_micro_com_wilcoxtest.txt",sep = '\t',row.names = T)

p <- ggboxplot(ah_total, x="Condition", y = "microbialload", color = "Condition", facet.by = "Genotype",
               palette = "jco", add = "jitter")
p

p_ttest <- p + stat_compare_means(method = "t.test", label.x = 1.5)
p_ttest
p_wtest <- p + stat_compare_means(method = "wilcox.test", label.x = 1.5)
p_wtest

# ggsave(paste("./result/stat/totalload_ah_micro_com_ttest.pdf", sep=""), p_ttest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_ah_micro_com_ttest.png", sep=""), p_ttest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_ah_micro_com_wilcoxtest.pdf", sep=""), p_wtest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_ah_micro_com_wilcoxtest.png", sep=""), p_wtest, width = 6, height = 6)

com_t <- compare_means( microbialload ~ Condition, data = hn_total, group.by = "Genotype",
                        method = "t.test" , paired = F)
# write.table(com_t, file = "./result/stat/totalload_hn_micro_com_ttest.txt",sep = '\t',row.names = T)
com_w <- compare_means( microbialload ~ Condition, data = hn_total, group.by = "Genotype",
                        method = "wilcox.test" , paired = F)
# write.table(com_w, file = "./result/stat/totalload_hn_micro_com_wilcoxtest.txt",sep = '\t',row.names = T)

p <- ggboxplot(hn_total, x="Condition", y = "microbialload", color = "Condition", facet.by = "Genotype",
               palette = "jco", add = "jitter")
p

p_ttest <- p + stat_compare_means(method = "t.test", label.x = 1.5)
p_ttest
p_wtest <- p + stat_compare_means(method = "wilcox.test", label.x = 1.5)
p_wtest
# 
# ggsave(paste("./result/stat/totalload_hn_micro_com_ttest.pdf", sep=""), p_ttest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_hn_micro_com_ttest.png", sep=""), p_ttest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_hn_micro_com_wilcoxtest.pdf", sep=""), p_wtest, width = 6, height = 6)
# ggsave(paste("./result/stat/totalload_hn_micro_com_wilcoxtest.png", sep=""), p_wtest, width = 6, height = 6)
```


## Fig 5b Metadata - Bacteria

```{r}
data5c = read.table("./data/Fig5b_new.txt",header = T, row.names = 1)
data5c_stat  = read.table("./data/Fig5b_new_stat.txt",header = T, row.names = 1)
 
com_5c_w <- compare_means( ratio ~ treatment, data = data5c, method = "wilcox.test", paired=FALSE,  group.by = "genotype")
com_5c_t <- compare_means( ratio ~ treatment, data = data5c, method = "t.test", paired=FALSE,  group.by = "genotype")
com_5c <- rbind(com_5c_w, com_5c_t)
head(com_5c)

p = ggplot(data5c_stat, aes(x = treatment, y = radio_mean)) + 
  geom_bar(stat = "identity",fill = "white", colour = "black", width=0.7, na.rm = TRUE)+ 
  geom_errorbar(aes(ymin= radio_mean - radio_error, ymax= radio_mean + radio_error), width=.1) + 
  facet_wrap(~genotype)+
  xlab("Groups")+
  ylab("Ratio of bacteria to host plant")+
  theme_bw()
p

```

## Fig 5c Metadata - Fungi

```{r}
data5c = read.table("data/Fig_5b_fungi_metadata.txt",header = T, row.names = 1)
data5c_stat  = read.table("data/Fig_5b_fungi_metadata_stat.txt",header = T, row.names = 1)

com_5c_w <- compare_means( ratio ~ treatment, data = data5c, method = "wilcox.test", paired=FALSE,  group.by = "genotype")
com_5c_t <- compare_means( ratio ~ treatment, data = data5c, method = "t.test", paired=FALSE,  group.by = "genotype")
com_5c <- rbind(com_5c_w, com_5c_t)
head(com_5c)

# write.table(com_5c, "./result/Fig_5b_fungi_compare_Wilcoxon_ttest.txt", col.names = T, row.names = F, sep="\t", quote=F)

p = ggplot(data5c_stat, aes(x = treatment, y = radio_mean)) + 
  geom_bar(stat = "identity",fill = "white", colour = "black", width=0.7, na.rm = TRUE)+ 
  geom_errorbar(aes(ymin= radio_mean - radio_error, ymax= radio_mean + radio_error), width=.1) + 
  facet_wrap(~genotype)+
  xlab("Groups")+
  ylab("Ratio of bacteria to host plant")+
  theme_bw()
p
# ggsave("./result/Fig_5b_fungi_metadata.png", p, width = 5, height = 4)
# ggsave("./result/Fig_5b_fungi_metadata.pdf", p, width = 5, height = 4)

```

## Fig5d-e


```{r}

### FIG5d - bacteria

corr <- read.table("data/Fig5d_bac_meta_ratio.txt", header = T)

x1 <- corr$ratio
y1 <- corr$load

cor.test(x1,y1,method="pearson")
lm.fit1 <- lm(y1~0+x1)
coef(lm.fit1)

plot(corr$ratio,corr$load,
     xlab =" Ratios of bacterial reads to host plant reads", 
     ylab ="Microbial load generated by HA-QAP")

abline(lm.fit1)

p <- ggplot(corr, aes(ratio, load)) +
  geom_point(size = 2.5) +
  theme_classic()+ scale_x_continuous(breaks=seq(0, 2, 0.2)) +
  theme_classic()+ scale_y_continuous(breaks=seq(0, 10, 2)) +
  geom_smooth(method = "glm", size = 0.8, colour = "grey10")+ expand_limits(x = 0.2, y = 0) + 
  labs(x="Ratios of bacterial reads to host plant reads", y="Microbial load generated by HA-QAP") 
p
# ggsave("./result/Fig5d_bac_meta_ratio_corr.pdf", p, width = 5, height = 4)
# ggsave("./result/Fig5d_bac_meta_ratio_corr.png", p, width = 5, height = 4)

```



```{r}
### FIG5e - fungi

corr <- read.table("data/Fig5e_fun_meta_ratio.txt", header = T)

x1 <- corr$ratio
y1 <- corr$load

cor.test(x1,y1,method="pearson")
lm.fit1 <- lm(y1~0+x1)
coef(lm.fit1)

plot(corr$ratio,corr$load,
     xlab =" Ratios of fungal reads to host plant reads", 
     ylab ="Microbial load generated by HA-QAP")

abline(lm.fit1)

p <- ggplot(corr, aes(ratio, load)) +
  geom_point(size = 2.5) +
  theme_classic()+ scale_x_continuous(breaks=seq(0, 0.006, 0.001)) +
  theme_classic()+ scale_y_continuous(breaks=seq(0, 2, 0.5)) +
  geom_smooth(method = "glm", size = 0.8, colour = "grey10")+ expand_limits(x = 0.001, y = 0) + 
  labs(x="Ratios of fungal reads to host plant reads", y="Microbial load generated by HA-QAP") 
p
# ggsave("./result/Fig5e_fun_meta_ratio_corr.pdf", p, width = 5, height = 4)
# ggsave("./result/Fig5e_fun_meta_ratio_corr.png", p, width = 5, height = 4)

```


## Fig 5f

```{r}
data <- read.csv("data/Fig5f-heatmap-p.csv", header = T)

## HN

data_hn <- dplyr::select(data, Bacteria, starts_with("HN"))

all <- gather(data_hn, key = group , value = logFC, `HN_MH_RA`:`HN_WYJ_AA`)

p_hn <- ggplot(all, aes(group, Bacteria)) + 
  geom_tile(aes(fill = logFC),colour = "grey50") + 
  scale_fill_gradient2(low = "#6D9EC1",high = "sandybrown", midpoint = 0)+
  theme(axis.text.x = element_text(angle = -45, vjust = 1, hjust = 0))+
  scale_y_discrete(limits=c("Gammaproteobacteria","Deltaproteobacteria","Betaproteobacteria",
                            "Alphaproteobacteria","Verrucomicrobia","Spirochaetes","Nitrospirae",
                            "Ignavibacteriae","Firmicutes","Chloroflexi","Bacteroidetes","Actinobacteria",
                            "Acidobacteria"))+
  scale_x_discrete(limits=c("HN_MH_RA","HN_MH_AA","HN_WYJ_RA","HN_WYJ_AA"))

p_hn

```


## Fig5h-j

```{r}
raotutab <- read.delim("data/otutab_ra_Fig5.txt", row.names= 1,  header=T, sep="\t")
aaotutab <- read.delim("data/otutab_aa_bac_usearch.txt", row.names= 1,  header=T, sep="\t")
# raotutab <- raotutab/10000
# colSums(raotutab)

design <- read.table("data/Fig5_design_bac.txt", header=T, row.names= 1, sep="\t") 

# Select by manual set group
if (TRUE){
  design = subset(design, Genotype %in% c("MH63","WYJ7DEP1"))
  # Set group order
  design$Genotype  = factor(design$Genotype, levels=c("MH63","WYJ7DEP1"))
}else{
  design = design
}

## remove points

myvars <- rownames(design) %in% c("Bac2DMH6303","Bac2DMH6309","Bac2DMH6310","Bac2DMH6311","Bac2WMH6304","Bac2WMH6308","Bac2WWYJ04","Bac2WWYJ10","Bac2WWYJ11","Bac2WWYJ14","BacDWYJ02","BacDWYJ05","BacDWYJ07","BacDWYJ10","BacWMH6301","BacWMH6307","BacWWYJ07","BacWWYJ14")
sub_design <- design[!myvars,]

ra_otutab_f <- raotutab[,colnames(raotutab) %in% rownames(sub_design)]
aa_otutab_f <- aaotutab[,colnames(aaotutab) %in% rownames(sub_design)]

```


```{r}
## OTU - "OTU_16","OTU_11","OTU_13"
idx <- c("OTU_16","OTU_11","OTU_13")
otu_ra_Data <- ra_otutab_f[idx,]
otu_aa_Data <- aa_otutab_f[idx,]

otu_ra <- as.data.frame(t(otu_ra_Data))
otu_aa <- as.data.frame(t(otu_aa_Data))

otu_ra <- merge(otu_ra, sub_design, by="row.names")
otu_aa <- merge(otu_aa, sub_design, by="row.names")

ra_database <- select(otu_ra, Row.names, OTU_16, OTU_11, OTU_13, type, site, Genotype, Other)
aa_database <- select(otu_aa, Row.names, OTU_16, OTU_11, OTU_13, type, site, Genotype, Other)

ra_tidy = gather(ra_database, key = OTUID , value = count, `OTU_16`:`OTU_13`)
aa_tidy = gather(aa_database, key = OTUID , value = count, `OTU_16`:`OTU_13`)

aamethod <- "aa"
ramethod <- "ra"

ra_table <- cbind(ra_tidy, ramethod)
colnames(ra_table)[8] <- "Method"

aa_table <- cbind(aa_tidy, aamethod)
colnames(aa_table)[8] <- "Method"

com_aara <- rbind(ra_table,aa_table)

com_aara_hn <- filter(com_aara, site == "Hn")
com_aara_hn_WYJ <- filter(com_aara_hn, Genotype == "WYJ7DEP1")
com_aara_hn_MH <- filter(com_aara_hn, Genotype == "MH63")

OTU16 <- dplyr::filter(com_aara_hn_MH, OTUID == "OTU_16")
OTU11 <- dplyr::filter(com_aara_hn_MH, OTUID == "OTU_11")
OTU13 <- dplyr::filter(com_aara_hn_WYJ, OTUID == "OTU_13")
# 
# write.table(ra_database, file = "./result/Fig5_com_ra_database.txt",sep = '\t',row.names = T)
# write.table(aa_database, file = "./result/Fig5_com_aa_database.txt",sep = '\t',row.names = T)

```


```{r}
### Fig5h

com_w_16 <- compare_means( count ~ Other, data = OTU16, group.by = "Method",
                        method = "wilcox.test" , paired = F)
# write.table(com_w_16, file = "./result/Fig5h_wilcoxtest.txt",sep = '\t',row.names = T)
p16 <- ggboxplot(OTU16, x="Other",y = "count",
               facet.by = "Method", scales = "free_y",  color = "Other", 
               order = c("dry","wet"), 
               palette="Dark2", add = "jitter", short.panel.labs = FALSE, title = "OTU_16")
p16 
p016 <- p16 + stat_compare_means(label =  "p.signif",  method = "wilcox.test",label.x = 1.55)
p016
# ggsave("./result/Fig5h_OTU16_wilcoxtest.pdf", p016, width = 5, height = 4)
# ggsave("./result/Fig5h_OTU16_wilcoxtest.png", p016, width = 5, height = 4)
```

```{r}
### Fig5i
com_w_11 <- compare_means( count ~ Other, data = OTU11, group.by = "Method",
                        method = "wilcox.test" , paired = F)
# write.table(com_w_11, file = "./result/Fig5i_wilcoxtest.txt",sep = '\t',row.names = T)

p11 <- ggboxplot(OTU11, x="Other",y = "count",
               facet.by = "Method", scales = "free_y",  color = "Other", 
               order = c("dry","wet"), 
               palette="Dark2", add = "jitter", short.panel.labs = FALSE, title = "OTU_11")
p11 
p011 <- p11 + stat_compare_means(label =  "p.signif",  method = "wilcox.test",label.x = 1.55)
p011
# ggsave("./result/Fig5i_OTU11_wilcoxtest.pdf", p011, width = 5, height = 4)
# ggsave("./result/Fig5i_OTU11_wilcoxtest.png", p011, width = 5, height = 4)
```


```{r}
### Fig5j
com_w_13 <- compare_means( count ~ Other, data = OTU13, group.by = "Method",
                        method = "wilcox.test" , paired = F)
# write.table(com_w_13, file = "./result/Fig5j_wilcoxtest.txt",sep = '\t',row.names = T)
p13 <- ggboxplot(OTU13, x="Other",y = "count",
               facet.by = "Method", scales = "free_y",  color = "Other", 
               order = c("dry","wet"), 
               palette="Dark2", add = "jitter", short.panel.labs = FALSE, title = "OTU_13")
p13 
p013 <- p13 + stat_compare_means(label =  "p.signif",  method = "wilcox.test",label.x = 1.55)
p013
# ggsave("./result/Fig5j_OTU13_wilcoxtest.pdf", p013, width = 5, height = 4)
# ggsave("./result/Fig5j_OTU13_wilcoxtest.png", p013, width = 5, height = 4)

```


```{r}
OTUid11 <- "OTU_11"
OTUid13 <- "OTU_13"
OTUid16 <- "OTU_16"

com_w_11 <- cbind(com_w_11, OTUid11)
com_w_13 <- cbind(com_w_13, OTUid13)
com_w_16 <- cbind(com_w_16, OTUid16)
colnames(com_w_11)[10] <- "OTUID"
colnames(com_w_13)[10] <- "OTUID"
colnames(com_w_16)[10] <- "OTUID"

compare_table <- rbind(com_w_11, com_w_13, com_w_16)
# write.table(compare_table, file = "./result/Fig5h5i5j_wilcoxtest.txt",sep = '\t',row.names = T)
```


